### ISSUE TITLE
[BUG] Initial Value returns Value

### ISSUE THREAD

**Issue by Denis347** [AdamRamberg/unity-atoms#103]
**Describe the bug**
Hi, sorry, if there's something I'm overlooking or understanding incorrectly.
If I want to get the Initial Value of any variable, I get current value (or just Value) instead.

**To Reproduce**
Create any variable. For example int variable. Set Initial Value to 5 in the editor. 
Then, click Play, and Value gets set to 5 as well correctly.
Then at runtime, change Value to anything, let's say 1. 
In the inspector, the Initial Value stays 5, which is correct. 
However, when trying to get the Initial Value in the code, via "myVar.InitialValue", it returns current Value (1), instead of Initial Value (5).

By scanning the code, it seems the issue is in the AtomVariable.cs, line 33:
`public T InitialValue { get { return _value; } }`

Here, the InitialValue is getting _value, instead of _initialValue, and I'm not quite sure why.

**Expected behavior**
"myVar.InitialValue" should return Initial Value, but returns current Value instead.

**Environment**
 - OS: Windows 10 x64
 - Unity Version 2019.3.0f6
 - Version of Unity Atoms v2.1.1

**Comment by soraphis** [comment]
this is correct.

I fixed it in https://github.com/AdamRamberg/unity-atoms/commit/1772b75ec578291745f56d79fadea0b9cf452d2b

@AdamRamberg sorry, was changing it on the web interface and thought github would make this change in my fork. I didn't realise I've had writing permissions here, sadly the commit message is now  sub optimal

**Comment by AdamRamberg** [comment]
@Denis347 Thanks for reporting the issue! @soraphis fix will be included in the next release of Unity Atoms. 

@soraphis No worries and thanks for fixing it ⭐️
