### ISSUE TITLE
[FEATURE][PROPOSAL] Instance specific events, variables, listeners

### ISSUE THREAD

**Issue by miikalo** [AdamRamberg/unity-atoms#105]
**Is your feature request related to a problem? Please describe.**
I want to have a prefab, such as an enemy unit, which consists of graphics, sounds, movement, etc. If a player then "hits" said enemy, I want to have the hit raise an event "HasBeenHit" to which each component of the instantiated unit (graphics, sounds, movement...) react accordingly and independent of each other. This allows me to later add more components, such as particle effects, without making changes to code and have them trigger on hit. This is doable and works well, but creating another instance of this prefab will obviously make both or all units react to the same event when any one of them is "hit".

**Describe the solution you'd like**
Instance specific sets of events and their listeners. Each unit would have their separate events, variables, and listeners. Then only the correct unit would react to the event when getting hit.

**Describe alternatives you've considered**
Some way of using the current implementation? I'm not sure of the terminology and I could not find similar discussions.

**Comment by soraphis** [comment]
> If a player then "hits" said enemy, I want to have the hit raise an event "HasBeenHit" to which each component of the instantiated unit

I'm not sure if UnityAtoms is the correct tool for this job, since unity can do this perfectly fine on its own: https://docs.unity3d.com/Manual/MessagingSystem.html

(it's exactly made for the explained use case)

> Instance specific sets of events and their listeners. Each unit would have their separate events, variables, and listeners. 

also this is a duplication to: https://github.com/AdamRamberg/unity-atoms/issues/53
