### ISSUE TITLE
[FEATURE]Re-add the old AtomListener x2 that supports different types in v3

### ISSUE THREAD

**Issue by nixvalentine** [AdamRamberg/unity-atoms#116]
Hi,

I'm trying to create a EventListener of <Vector3, Int> in v3 unsuccessfully and being told it is impossible for v3.

It is possible in v2. I'm not sure how to proceed on this so this is all I can say. I'll try work around with structs.

Tks and Best regards,
Nix,

**Comment by AdamRamberg** [comment]
Thanks for reporting! This will be addressed in the next release of Atoms.

**Comment by AdamRamberg** [comment]
Has been addressed in v4 of Unity Atoms. I suggest using v4 instead of v3.
