### ISSUE TITLE
[FEATURE] Using TextArea attribute for Developer Description

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#127]
Really small fix
I think it looks better when we use TextArea attribute instead of Multiline for a developer description. TextArea supports scrollable area and word wrap mode.

Old look
![obraz](https://user-images.githubusercontent.com/51023959/79699474-22dc8400-8290-11ea-83a0-51f1b00c8200.png)

New look
![obraz](https://user-images.githubusercontent.com/51023959/79699491-3b4c9e80-8290-11ea-9cf1-9f15e2309e12.png)

#128

**Comment by AdamRamberg** [comment]
Thanks for submitting! Will take a look at the PR later today.
