### ISSUE TITLE
[feature] Make usage of the package-manager

### ISSUE THREAD

**Issue by soraphis** [AdamRamberg/unity-atoms#13]
hey, i highly refactored the project in my fork: https://github.com/soraphis/unity-atoms/tree/stable

i made this to have the source files in the root directory, so i could add a package.json.

i updated the readme and added how to install it with the package-manager in unity 2018.3+
(more information about that can be found [here](https://forum.unity.com/threads/git-support-on-package-manager.573673/) and [here](https://gist.github.com/LotteMakesStuff/6e02e0ea303030517a071a1c81eb016e) )

i don't know if this is a way you wanna go with your tool / repository, thats why i have not created a pull request for this changes

**Comment by AdamRamberg** [comment]
Have just heard whispers of this before, didn't know that it was possible to use a package.json. Being a web dev I love this 😺 

Hope you don't mind, but will try to implement this myself. Think it is important to know what is going on. If successful I will commit the changes to v1.0.0. I'm using the library in my current game, so I also want to make sure that I will be able to migrate to this new structure. 

Do you know the workflow for when developing a package like this? It's not possible to open the repository directly in Unity, so I guess you would need a test Unity project where you in your manifest point to your local version of the library. Or any other ideas? Just realized that it might me a good idea to have a Unity project inside the repo, but not at the top level and that is not included in the package itself 🤔

**Comment by soraphis** [comment]
What I've done: (btw if you start with an empty project this is much easier, because you can just `git init` inside the Assets folder)
I moved the whole project folder inside a new folder "unity-atoms-wrapper" and inside the subfolder "Assets". so for unity the new project will be the wrapper, while the git repository is inside the Assets folder.

Then i moved everything that isn't a source file (e.g. the ProjectSettings folder, ...) into the wrapper directory.
I also removed the UnityAtoms folder inside Assets, because it is an unnecessary nesting.

I moved the Editor folder and Tests, Examples folder to the Assets folder and Everything else into an Source folder.

and i used the package.json to only include Editor, Source and License files. since i would not want to be examples or tests in a package.
Also i added assembly definitions for all the specific folders. 

____________
On a new Project:

- Unity Project Folder
   - Assets
       - (git init here, also .gitignore and .gitattributes if needed)
       - Editor
           - *.asmdef for editor stuff
       - Tests
           - *.asmdef for test stuff
       - Source
       - *.asmdef for the entire package
       - LICENSE
       - README (since this is the git projects root)
       - package.json

**Comment by AdamRamberg** [comment]
Implemented in this commit: a3ea1a133bf6727e011ba85c64569db45302e487

Think it is better to have an example Unity project as a subfolder of the repo in order to work on the library. Of course this project will be excluded from the package. Will create a new issue for adding the project.

**Comment by soraphis** [comment]
> Think it is better to have an example Unity project as a subfolder of the repo in order to work on the library. 

yeah, in my fork i did not delete the examples, i just excluded them from the package, they are still in git

**Comment by AdamRamberg** [comment]
Did you manage to exclude folders in the package.json file? Seems like Unity's package manager is ignoring what I add to the "files" array in the package.json

**Comment by soraphis** [comment]
with my fork, in Unity 2018.3.7f1:

![grafik](https://user-images.githubusercontent.com/3066582/54029663-73d30b00-41a9-11e9-974f-f3ad7f620629.png)

some of the package.json features are ignored by unity, even more so in older versions

if i add this to the package manager:

`    "com.mambojambostudios.unityatoms": "https://github.com/AdamRamberg/unity-atoms.git#a3ea1a1", `

it works fine, too (same structure as in the image above, but its definitely your repo because i refactored my fork to a very different folder structure).

note that the last part after the `#` is an identifier, if you name your branches and your tags the same i don't know how that is resolved. (because you have a branch "v1.0.0" and at somepoint there might also be a tag "v.1.0.0").

**Comment by AdamRamberg** [comment]
Hmm alright. Might be that I add Unity Atoms as a local file instead of via the github repo URL. Will have to fiddle around a little bit more.
