### ISSUE TITLE
How does unity-atoms compare to ScriptableObject-Architecture by Daniel Everland ?

### ISSUE THREAD

**Issue by irmo322** [AdamRamberg/unity-atoms#130]
**State your question below**
How does unity-atoms differ from [ScriptableObject-Architecture](https://github.com/DanielEverland/ScriptableObject-Architecture) ?
What should be considered before choosing between the two ?

**Add any additional information / background**
After watching Ryan Hipple's talk, I searched the web for implementations of the patterns he explained. unity-atoms and ScriptableObject-Architecture are the only two that seem both mature and well maintained.
As an amateur unity developer, I don't have enough experience to decide which one I should use.

**Comment by irmo322** [comment]
I've open a similar issue in ScriptableObject-Architecture repository: https://github.com/DanielEverland/ScriptableObject-Architecture/issues/120

**Comment by AdamRamberg** [comment]
Hi @irmo322! 

Awesome to hear that you found this library after watching that talk :) 

I knew that [ScriptableObject-Architecture](https://github.com/DanielEverland/ScriptableObject-Architecture) existed, but have never tried it before. This is maybe a boring answer, but I would suggest you to make 2 version of a simple sample scene using Unity Atoms and ScriptableObject-Architecture and then after that decide which one is the best fit for you. 

Let me know if you have any specific questions regarding Unity Atoms! I would also suggest you to join the [Discord](https://discord.gg/W4yd7E7) channel to chat with other users of Unity Atoms.

**Comment by Robert-Oost** [comment]
I have tried working with SO Architecture, and just found out about this package. Right off the bat, I notice Unity Atom's Variable instancers and Event instancers which SO seems to be lacking. I'll be testing Atoms this week, so I might give a better comparison later.

**Comment by xvnnnk** [comment]
SO Architecture has better event handling, Untiy Atoms has better Variable handling. 
In SO Architecture you can see event's stacktrace. 
In Unity Atoms you have variable instancing.

**Comment by Robert-Oost** [comment]
A lot of the differences I could spot immediately by comparing the respective feature pages for the assets. Variables have their own Changed events that can easily be subscribed to, eliminating some boilerplate code that would have been necessary with SO Architecture. There's even UniRx compatability.

Both assets have some UI trouble with custom structs sometimes. SO Architecture's code generator is faster, but it also has fewer options. It also allow you to specify a sub-menu for creating your custom assets, so the create asset menu doesn't look so cluttered.

Finally, Unity Atoms does seem to have a more cohesive community surrounding it, especially with the discord server. For any further differences, the docs for both assets paint a pretty good picture, I recommend you at least read those for yourself before deciding.

**Comment by AdamRamberg** [comment]
Very interesting to hear about the differences. 

@xvnnnk How is SO Architecture better at event handling? Maybe there are lessons we can learn from SO Arch and incorporate into Atoms (if it makes sense and is feasible). 

@Robert-Oost What UI troubles do you experience with custom structs in Atoms?

**Comment by stgrosshh** [comment]
Just started to try out both assets, since I'm pretty new in Unity development ( in an industrial application context, not gaming).
I definitely like the event stack trace feature in SO Architecture.
On the other hand unity-atoms has more features and I like the in context creation in the inspector.

What I really like is the developer description property included in the very base class!

This is a feature I still miss as a standard property for Game Objects in Unity (and their composition). Coming from an industrial background with long living applications this is still a must to enable easy reasoning about code implemented by other developers.

**Comment by ThimoDEV** [comment]
I've looked through the ScriptableObject architecture and there are a few differences that I noticed.

- Scriptableobject architecture has a few more variable types in its create menu.
- Scriptableobject architecture has different game event types in its create menu.
- The scriptableobject architecture has a collapse button to hide the stacktrace during debugging.
- The scriptableobject architecture has a clamp option built in the variable scriptableobject. Unity atoms has only a clamp feature for int or float I believe (correct me if i'm wrong).

- The scriptableobject architecture has a stacktrace in its event listeners.
- The scriptableobject architecture has a visual event debugging feature. It is possible to draw a line in debug mode for each event. You will see your event moving across that line when it is called.

Unity atoms is currently a more complete scriptableobject project. Most features are more advanced in atoms as far as I can see. The only big difference scriptableobject architecture has is its visual event tracking.

![Visual-debugging](https://user-images.githubusercontent.com/68739517/89453395-7bf8f680-d75f-11ea-9c65-eddfb26561a1.gif)

**Comment by ThimoVBE** [comment]
[FAQ-Unity_Atoms.txt](https://github.com/AdamRamberg/unity-atoms/files/5366704/FAQ-Unity_Atoms.txt)

I made a first version for a possible Unity Atoms FAQ. I upload it here because I don't know exactly how to edit the docs. Let me know if things should change.

**Comment by AdamRamberg** [comment]
@miikalo PR has been merged to canary. Closing this issue.
