### ISSUE TITLE
[FEATURE] AtomVariable Force Change handler on SetValue (even if not changed)

### ISSUE THREAD

**Issue by soraphis** [AdamRamberg/unity-atoms#131]
**Is your feature request related to a problem? Please describe.**

`MyAtomVariable.Value = MyAtomVariable.Value` will not raise change events.
this is fine for most cases, but in some cases it could be desired.

**Describe the solution you'd like**
changing the SetValue method in https://github.com/AdamRamberg/unity-atoms/blob/master/Packages/Core/Runtime/Variables/AtomVariable.cs#L121

to allow passing a "forceEvent" parameter: `SetValue(T newValue, bool forceEvent = false)`

**Additional context**
asked via discord:

```
ScriptA:
if(getKeyDown(A)) MyInVariable.Value = 1
```

> I've setup a IntEvent that's tied to the variable and I'm using a listener to act on the change. However, how can I get the listener to trigger everytime the variable is "set". ScriptA would only trigger the listener once as the variable isint changed but Id like it to still be called. Any ideas?! Many thanks

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! This change sounds good to me. Let's add it in the next minior release of Atoms.

**Comment by AdamRamberg** [comment]
Fixed in #157
