### ISSUE TITLE
[FEATURE] AtomReference members are private

### ISSUE THREAD

**Issue by soraphis** [AdamRamberg/unity-atoms#132]
**Is your feature request related to a problem? Please describe.**
register an event to an AtomReference is not possible via code, since the members are private and there are no getters.
https://github.com/AdamRamberg/unity-atoms/blob/master/Packages/Core/Runtime/References/AtomReference.cs

**Describe the solution you'd like**
Add public getters, which throw errors if the `usage type` does not match.

**Additional context**
Asked via discord:
> Is there any way to register an action to a Reference within a script? I'm able to register to an Instancer with myInstancer.Variable.Changed.Register(myAction);, but not a Reference. Am I missing something?

**Comment by AdamRamberg** [comment]
Sounds good to me! Let's add it in the next version of Unity Atoms! :)

**Comment by AdamRamberg** [comment]
Fixed in #158
