### ISSUE TITLE
[BUG] Code generation - Unchecking options has no effect on generated results

### ISSUE THREAD

**Issue by Robert-Oost** [AdamRamberg/unity-atoms#133]
**Describe the bug**
When using the code generator, all options are generated despite some of them being manually unchecked. 

**To Reproduce**

1. Open the Code generator
2. Uncheck some of the values. 
3. Click generate and wait a while.
4. Go to the folder with the generated files.

**Expected behavior**
Types that were unchecked are still generated.

**Screenshots**
This was my configuration:
![image](https://user-images.githubusercontent.com/39600335/80456262-95530100-892d-11ea-88a3-a2e4911fa4e7.png)
These were my results:
![image](https://user-images.githubusercontent.com/39600335/80456393-c92e2680-892d-11ea-97f1-12d30e8e9e6d.png)

**Environment**
 - OS: Windows 10
 - Unity Version 2019.3.11.f
 - Version of Unity Atoms [e.g. v4.1.0]

**Comment by AdamRamberg** [comment]
Thanks for taking the time to report this issue! Will take a look at it when I have the time or if you (or someone else) is up for it then a PR would very much appreciated.

**Comment by AdamRamberg** [comment]
Fixed in #147. Will be included in the next release of Atoms.
