### ISSUE TITLE
[BUG] Duplication check in ValueLists

### ISSUE THREAD

**Issue by mnarimani** [AdamRamberg/unity-atoms#141]
**Describe the bug**
ValueLists implement `IList<T>` not `ISet<T>`. So they should behave like `List<T>` not `HashSet<T>`. They should have no problem with having duplicate elements in them. 
This line:
https://github.com/AdamRamberg/unity-atoms/blob/ce9e818ac3d9315364ebf539926597a77a5adb85/Packages/Core/Runtime/ValueLists/AtomValueList.cs#L51
Should be removed.

**Comment by AdamRamberg** [comment]
Hi @mnarimani! Thanks for this issue. This change sounds sane. Would you mind submitting a PR for this against the canary branch?

**Comment by mnarimani** [comment]
> Hi @mnarimani! Thanks for this issue. This change sounds sane. Would you mind submitting a PR for this against the canary branch?

Sure.

**Comment by AdamRamberg** [comment]
Fixed in #144. Closing the issue.
