### ISSUE TITLE
[QUESTION] On Trigger Mono Hook & Collider2D Event - invoke single method

### ISSUE THREAD

**Issue by ppozniak** [AdamRamberg/unity-atoms#150]
Hello there. Thanks for this great library.
I am trying to understand OnTrigger MonoHook better along with Collider listeners.

Game scenario: Randomly instantiated barrels that player can destroy on collide.
When I tried to follow the tutorial from documentation I ended up with a situation where colliding with one barrel **destroys all of them** at the same time. (I don't want to use Actions, just a method from different MonoBehaviour).

Where my intention is to obviously destroy only one barrel, that was touched,
_(note: not gameObject Destroy, but a custom Destroy method)_

![image](https://user-images.githubusercontent.com/13921243/81185798-f1f79100-8fa9-11ea-826d-b0a4c0d2fdba.png)

---
The only way I could think of is using `Collider2DGameObject`, getting the component and running it's Destroy method, but that just doesn't feel right.
I guess I could also compare game object from the event with the component's gameObject 🤷 but still I would have this bad feeling.
```c#
  public void HandleColliderEvent(Collider2DGameObject colliderEvent)
  {
    if (colliderEvent.Collider2D.CompareTag("Player"))
    {
      colliderEvent.GameObject.GetComponent<DestructableController>().Destroy();
    }
  }
```

My question is: Is there a better way to do it?
Was the system meant to be used mainly by Managers, that would hold references to multiple objects? Or I am just missing something?

---
How I solved it before
In my previous system I have done something similar to MonoHooks. It consisted of two parts:

1. Trigger invoker, which had a "Tag" property (It was scriptableobject)
2. Trigger listener, which had a list of tag - UnityEvent mapping.

So player would have an TriggerInvoker with Player tag.
Barrel would have trigger listener, that would listen for colliding with Player, and just run the method.

Hopefully it's clear enough.
Thank you.

**Comment by soraphis** [comment]
MonoHooks isn't exactly my area of expertise, but just from looking into your description:

all barrels seem to use the same event, so all barrels will react to it on the same time. 
you probably want to use an `Collider2DEventInstancer` such that each gameobject will get its own event.

Next is to change both of your Event References to use Instancers instead of direct variables. (`⋮` icon)

**Comment by AdamRamberg** [comment]
Hi there! 

@soraphis is right. In this case you need an Collider2D Event that is specific for your Barrel instance. Attach a `Collider2DEventInstancer` to your barrel and give it a base event, which the in memory Collider 2D Event is going to be created from. Then reference the `Collider2DEventInstancer` in both `OnTrigger2DHook` and in `Collider2DEventReferenceListener`. 

This technique is used in the [InfiniteWaves](https://github.com/AdamRamberg/unity-atoms/tree/master/Examples/Assets/InfiniteWaves) demo scene in the [Example](https://github.com/AdamRamberg/unity-atoms/tree/master/Examples) project. 

Closing this issue, but reopen if you need more help.
