### ISSUE TITLE
[BUG] Custom reference doesn't appear properly

### ISSUE THREAD

**Issue by bguyl** [AdamRamberg/unity-atoms#153]
**Describe the bug**
I generated Atom files for a custom struct and when I put a reference in a Monobehavior, 
when `Use Value` is selected, the drawer doesn't appear properly.

**To Reproduce**
1. Create a new Unity project and install Atom Core and Atom Base Atoms
2. Create a simple struct (eg [gist](https://gist.github.com/bguyl/efa9cd8a283346aa1597a713f60ef03f))
3. Clic on Tools > Unity Atoms > Generator, leave all the default values but fill the Type Name field with the struct name and clic generate.
4. Create a reference field in a MonoBehavior and select it: [gist](https://gist.github.com/bguyl/73223fef1bc108b858b9a56b937fe7fa) 

**Expected behavior**
It should show the default drawer for the struct correctly.

**Screenshots**
Folded
![image](https://user-images.githubusercontent.com/24865257/81389355-fb077000-9119-11ea-91eb-cd01eec71470.png)

Unfolded
![image](https://user-images.githubusercontent.com/24865257/81389395-0ce91300-911a-11ea-85fc-d75631961a0d.png)

Correct variable drawer
![image](https://user-images.githubusercontent.com/24865257/81389455-2722f100-911a-11ea-9f65-942e28c2c34e.png)

**Environment**
 - Unity Version: 2019.3.13f1
 - Version of Unity Atoms: 4.1.0

**Comment by bguyl** [comment]
I made several tests to fix this issue, you can find them in [this commit](https://github.com/bguyl/unity-atoms/commit/6f3be47222511d2d3fde5cf292252aa3bceaf5e3)

## Proposal 1 : Include chidren and draw to original rect
![test1](https://user-images.githubusercontent.com/24865257/81422586-70436700-9153-11ea-9168-80d47dc2ca8d.png)
Not viable if the value is on a single line (1st line is an IntReference)

## Proposal 1 + extra : Only if the value have children
![test1-extra](https://user-images.githubusercontent.com/24865257/81422877-e647ce00-9153-11ea-80f2-3556e83774a9.png)

## Proposal 2 : Show the value under the reference field
![test2](https://user-images.githubusercontent.com/24865257/81422928-fbbcf800-9153-11ea-8241-994bc253ef44.png)
Drawback: This is less compact, in particular for single line values

## Proposal 2 - extra : Add a visual hint to fill the blank
![test2-extra](https://user-images.githubusercontent.com/24865257/81423073-36269500-9154-11ea-825f-3192816baa30.png)

Also, proposal 2 could be combinated with extra 1

**Comment by AdamRamberg** [comment]
Thanks for this issue @bguyl! Really nice that you made some suggestions. I vote for doing **Proposal 1 + extra : Only if the value have children**, this to me seems to be the cleanest approach and leaves the drawer nice and compact for most cases (single line types). Would you mind creating a PR for **Proposal 1 + extra**?

**Comment by AdamRamberg** [comment]
Fixed in #155
