### ISSUE TITLE
[BUG] fsm.Machine.OnFixedUpdate does not execute.

### ISSUE THREAD

**Issue by icaro56** [AdamRamberg/unity-atoms#160]
**Describe the bug**
I'm using the FSM module to implement the basic movement of a character. When I call the FSM.Machine.OnUpdate function and place a Debug.Log inside, the log is printed, but when I use FSM.Machine.OnFixedUpdate the log is not printed.

**To Reproduce**
1. Create a FSM
2. Implement the OnFixedUpdate

```
FSM.Machine.OnFixedUpdate((deltaTime, value) => 
{
	Debug.Log("success");

}, gameObject);
```

**Expected behavior**
Print the log

**Environment**
 - OS: [e.g. iOS] Windows 10
 - Unity Version 2019.3
 - Version of Unity Atoms v4.1.0

**Comment by AdamRamberg** [comment]
Hi there! Thanks for reporting this bug. Just pushed a fix to the Canary branch so this will work in the next release of Unity Atoms.
