### ISSUE TITLE
[BUG] Unity 2020.1.0b12 Build Error

### ISSUE THREAD

**Issue by TforTrevor** [AdamRamberg/unity-atoms#166]
"The name 'StackTraces' does not exist in the current context"
![image](https://user-images.githubusercontent.com/36804391/85250372-5ff5fb80-b424-11ea-848e-30c6c8d72e85.png)

**Comment by AdamRamberg** [comment]
Hi there! 

I would like you to do the following: 
1) Try to install v4.2.1. Does that solve your issue?
2) If not, could you please try to "Reimport all" in Unity. 
3) If that still doesn't solve your issue could you please provide med the Unity version you are running, the operating system you are running and steps to reproduce (eg. do you get the error when you import the library or when building for example).

**Comment by TforTrevor** [comment]
v4.2.1 solved my issue. Thank you for being so quick to respond!
