### ISSUE TITLE
Serializable not needed for ScriptableObject

### ISSUE THREAD

**Issue by rakkarage** [AdamRamberg/unity-atoms#17]
Not really an issue but...
I am pretty sure the Serializable attribute is not needed on ScriptableObjects?
Thanks

**Comment by AdamRamberg** [comment]
Removed some unnecessary Serializable attributes in commit 847eff037204d841546c0da772d2f341f9cf1e25. They are still needed in most cases though (when implementing generic base classes, eg. BoolEvent).
