### ISSUE TITLE
[FEATURE] Optional base atom for Event Instancers

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#170]
**Is your feature request related to a problem? Please describe.**
It's frustrating having to create/choose a base AtomEvent whenever using an EventInstancer, especially since most of the cases they are the same.

**Describe the solution you'd like**
I'd like to be able to not add any base events and it still work (I understand the rare usecase for base events)

**Describe alternatives you've considered**
The solutions I thought of were either removing the base event entirely, or making a null check and instantiating a new event of the required type at runtime

**Comment by AdamRamberg** [comment]
Thanks for this issue! This sounds good to me. Just use [CreateInstance](https://docs.unity3d.com/ScriptReference/ScriptableObject.CreateInstance.html?_ga=2.4441459.1741528851.1593526292-1004207990.1591391081) if `_base` is null. The one doing this change will also need to remove the assert on OnEnable. I will label this issue "ready to be developed", so whoever feels motivated could grab it and start develop it

**Comment by mutmedia** [comment]
#172

**Comment by AdamRamberg** [comment]
Closed by #172
