### ISSUE TITLE
[FEATURE] public Raise functionality for EventInstancer

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#171]
**Is your feature request related to a problem? Please describe.**
It is not possible to raise an EventInstancer event through the editor

**Describe the solution you'd like**
It would be interesting if EventInstancers behaved just like regular events even more so if it was possible to create event instancers with custom logic.

**Describe alternatives you've considered**
Creating a Raise() and Raise(T item) in the base event instancer would solve this issue

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! 

So from my understanding the changes needed are the following: 
- Add a `Raise()` method and `Raise(T item)` method for the base event instancer. 
- Add a Raise button and a Inspector Raise Value field to custom editor for Event Instancers. 

Am I missing or missunderstanding anything?

**Comment by mutmedia** [comment]
Did not think about the custom editor Raise Button and Value, can also add that to the PR I submitted

**Comment by AdamRamberg** [comment]
Closed by #172
