### ISSUE TITLE
[FEATURE] Value List could have a StartCleared field or something like this

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#175]
**Is your feature request related to a problem? Please describe.**
It's annoying to have to create a script to manually clear value lists

**Describe the solution you'd like**
An option like variables have their initial values, list could have an option to start empty.

**Describe alternatives you've considered**
Writing scripts to clear the ValueList on awake

**Comment by AdamRamberg** [comment]
Hi @mutmedia! Sounds good to me! Wouldn't mind a PR on this if you are up for it :)

**Comment by AdamRamberg** [comment]
Closed in #180
