### ISSUE TITLE
IGameEvent<T1, T2> RegisterListener

### ISSUE THREAD

**Issue by rakkarage** [AdamRamberg/unity-atoms#18]
https://github.com/AdamRamberg/unity-atoms/blob/v1.0.0/Source/Base/IGameEvent.cs

should the multiple parameter version have the register and unregister? or they are supposed to be derived from each other?

Thanks

**Comment by AdamRamberg** [comment]
Register and Unregister are both missing. Good catch! ⭐ Fixed in commit: 593b275e6394b9d589de8a7a20375145dfc4aa84
