### ISSUE TITLE
IntListener (And maybe others) responses not passing through variable

### ISSUE THREAD

**Issue by akoolenbourke** [AdamRamberg/unity-atoms#19]
I testing the library and using a Changed event on a FloatVariable, listening to it with a FloatListener in another GameObject and in the FloatListener calling a response to a function in the destination object/script that accepts a float. What I get in the inspector though is a field appearing under the script name and that value is the value passed through to my script, not the incoming value from the event.

Any idea what I'm doing wrong? I seems as though I've set everything up just like the Medium post and in the Medium post the listener response to HealthChanged doesn't have a field under it.

![UNityAtomsProblem](https://user-images.githubusercontent.com/29034122/54092141-7625a700-43ed-11e9-82b4-5fc42f4f3b69.png)

Cheers
Aaron

**Comment by akoolenbourke** [comment]
On further investigation I think this is user error. I noticed later than the drop down for the target function actually has a section at the top where with "Dynamic". Selecting this had the desired effect.

**Comment by AdamRamberg** [comment]
Hi @akoolenbourke! So sorry for the late reply. Yes, you answered your own question, you need to choose a dynamic parameter in order for it to work properly :)

**Comment by Skelly1983** [comment]
This resolved the issue for me as well although I feel the article on medium should be updated as it is not stated to select the method listed under dynamic.

**Comment by AdamRamberg** [comment]
@Skelly1983 Great tip! The blog post has been updated.
