### ISSUE TITLE
[BUG] Compatibility issues with the new Enter Play Mode settings

### ISSUE THREAD

**Issue by TowerCrow** [AdamRamberg/unity-atoms#195]
Incompatibility with the new Enter Play Mode Settings.

1. Go to Project Settings/Editor and enable Enter Play Mode Options (with scene reload and domain reload disabled)
2. Create a new float atom variable and set InitialValue to 1f at edit time.
3. Hit Play and notice that Value remains at 0.

Expected behaviour would be that Value = InitialValue when entering Play mode.

**Environment**
 - OS: Windows 10 Pro Editor
 - Unity 2019.4.11f1
 - Unity Atoms 4.3.0

**Comment by soraphis** [comment]
https://github.com/AdamRamberg/unity-atoms/pull/182
