### ISSUE TITLE
[BUG] Null Reference Exceptions when trying to set VoidBaseEventReferenceListener event in code

### ISSUE THREAD

**Issue by TowerCrow** [AdamRamberg/unity-atoms#196]
**Describe the bug**
I'm trying to automatize the process of adding event listeners via an editor button, but I can't set Void Base Event Reference Listener event via code. I get a Null Reference Exceptions: https://pastebin.com/bCfckLJy and https://pastebin.com/EGVbC1qH

**To Reproduce**

Add the following script and run it. I'm triggering a more complex version of this at edit time with Odin Inspector's [Button] attribute but for testing purposes I placed the logic in Start.

```
using UnityAtoms.BaseAtoms;
using UnityEngine;

public class Test : MonoBehaviour
{
    public VoidEvent voidEvent;

    private void Start()
    {
        AddEventToListener();
    }
    private void AddEventToListener()
    {
        if (voidEvent!=null)
        {
            var go = new GameObject("Void Event Reference Listener",typeof(VoidBaseEventReferenceListener));
            var listener = go.GetComponent<VoidBaseEventReferenceListener>();
            listener.Event = voidEvent;
        }
    }
}
```

**Expected behavior**
The expected behaviour would be to not get null reference exeptions since the code is valid.

**Environment**
 - OS: Windows 10 Pro Editor, Desktop target
 - Unity Version 2019.4.11f1
 - Version of Unity Atoms [4.3.0]

**Comment by soraphis** [comment]
`listener` is null ... not `voidEvent` which is obviously the case, because GetComponent did not found a  VoidBaseEventReferenceListener. 

I'll do a few tests. give me a moment

**Comment by soraphis** [comment]
ok, I tried it myself and it is indeed the case.

it seems to be this line:

https://github.com/AdamRamberg/unity-atoms/blob/e2bc533807c3b47b0bae2123bed85c0e0900611f/Packages/Core/Runtime/Listeners/AtomEventReferenceListener.cs#L29

which makes the reference instantiate as default ( = null)

**Comment by miikalo** [comment]
Fixed on canary.
