### ISSUE TITLE
[BUG] UnregisterAll in AtomEvent does not seem to work

### ISSUE THREAD

**Issue by brandolori** [AdamRamberg/unity-atoms#200]
**Describe the bug**
Calling the `UnregisterAll` method does not seem to work at all, as the Actions keep getting executed upon a `Raise`.

**To Reproduce**
1. Register some Actions to a AtomEvent (in my case a VoidEvent), via the `Register(action)` method
2. Call `UnregisterAll` on the AtomEvent
3. Call `Raise()` on the AtomEvent
4. The Actions are still getting executed!

**Expected behavior**
The Actions should not get executed, and the only way to currently make it happen is to explicitly `Unregister(action)` each of them

**Environment**
 - OS: Windows, in-editor play
 - Unity Version: 2019.4.11f
 - Version of Unity Atoms: 4.3.0

**Comment by soraphis** [comment]
note that there is a difference between:

        voidEvent.Register(((Void t) => {Debug.Log("HeY");}));

and 

        voidEvent.Register((() => {Debug.Log("HeY");}));

The first one, is the Register on the `AtomEvent` Action<T> the second one is registering to the `AtomEventBase` .

UnregisterAll does currently only "unregister" on the AtomEvent.

to further note: it das not actually unregister them, the event is set to null 

https://github.com/AdamRamberg/unity-atoms/blob/9dd7f918a82e650f6831f3cfbce7894b7159455d/Packages/Core/Runtime/Events/AtomEvent.cs#L102

**Comment by miikalo** [comment]
Fixed on canary.
