### ISSUE TITLE
[QUESTION] Where are the listeners?

### ISSUE THREAD

**Issue by samueljonasson** [AdamRamberg/unity-atoms#203]
**State your question below**
Are the Listener components deprecated?

**Add any additional information / background**
I think I must be missing something.  I can't find the listener components in a fresh setup of Atoms.  Not even the IntListener that is specifically mentioned in the documentation.  Should we always be using the IntEventReferenceListener instead?

It looks like Listeners are also missing from the generator. There is only an Event Reference Listener.

**Comment by soraphis** [comment]
How did you install unity atoms?

make sure to also include `com.mambojambostudios.unity-atoms-base-atoms` and not only the `core` package

**Comment by samueljonasson** [comment]
I followed the guide by adding these to the manifest file:
![registry](https://user-images.githubusercontent.com/1074267/96142872-14df8700-0ef2-11eb-9d6c-69aa7707922e.png)
![dependencies](https://user-images.githubusercontent.com/1074267/96142884-17da7780-0ef2-11eb-9da8-9770c48ee76b.png)

It installed fine and this is what I have in the packages folder and as you can the there are "Listeners" in Core - but not in Base
![packages](https://user-images.githubusercontent.com/1074267/96142897-19a43b00-0ef2-11eb-9c5e-6393241d09a3.png)

**Comment by soraphis** [comment]
hm ... just cloned the package via npm... all files are there.
could you show me the whole manifest file?

**Comment by samueljonasson** [comment]
`{
  "scopedRegistries": [
    {
		"name": "Packages from jillejr",
		"url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
		"scopes": [
		"jillejr"
		]
    },
	{
		"name": "NPM Registry",
		"url": "https://registry.npmjs.org",
		"scopes": [
			"com.mambojambostudios.unity-atoms-core",
			"com.mambojambostudios.unity-atoms-base-atoms",
			"com.mambojambostudios.unity-atoms-fsm",
			"com.mambojambostudios.unity-atoms-mobile",
			"com.mambojambostudios.unity-atoms-mono-hooks",
			"com.mambojambostudios.unity-atoms-tags",
			"com.mambojambostudios.unity-atoms-scene-mgmt",
			"com.mambojambostudios.unity-atoms-ui"D
		]
	}
  ],
  "dependencies": {

	"com.mambojambostudios.unity-atoms-core": "4.3.0",
	"com.mambojambostudios.unity-atoms-base-atoms": "4.3.0",
	"com.mambojambostudios.unity-atoms-mono-hooks": "4.3.0",

	"jillejr.newtonsoft.json-for-unity": "12.0.301",
	
	
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.2.2",
    "com.unity.postprocessing": "2.3.0",
    "com.unity.probuilder": "4.2.3",
    "com.unity.render-pipelines.universal": "7.3.1",
    "com.unity.test-framework": "1.1.3",
    "com.unity.textmeshpro": "2.1.1",
    "com.unity.timeline": "1.2.14",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualeffectgraph": "7.3.1",
    "com.unity.xr.interaction.toolkit": "0.9.4-preview",
    "com.unity.xr.legacyinputhelpers": "2.1.4",
    "com.unity.xr.management": "3.2.15",
    "com.unity.xr.oculus": "1.4.3",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
`

**Comment by samueljonasson** [comment]
{
  "scopedRegistries": [
    {
		"name": "Packages from jillejr",
		"url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
		"scopes": [
		"jillejr"
		]
    },
	{
		"name": "NPM Registry",
		"url": "https://registry.npmjs.org",
		"scopes": [
			"com.mambojambostudios.unity-atoms-core",
			"com.mambojambostudios.unity-atoms-base-atoms",
			"com.mambojambostudios.unity-atoms-fsm",
			"com.mambojambostudios.unity-atoms-mobile",
			"com.mambojambostudios.unity-atoms-mono-hooks",
			"com.mambojambostudios.unity-atoms-tags",
			"com.mambojambostudios.unity-atoms-scene-mgmt",
			"com.mambojambostudios.unity-atoms-ui"D
		]
	}
  ],
  "dependencies": {

	"com.mambojambostudios.unity-atoms-core": "4.3.0",
	"com.mambojambostudios.unity-atoms-base-atoms": "4.3.0",
	"com.mambojambostudios.unity-atoms-mono-hooks": "4.3.0",

	"jillejr.newtonsoft.json-for-unity": "12.0.301",
	
	
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.2.2",
    "com.unity.postprocessing": "2.3.0",
    "com.unity.probuilder": "4.2.3",
    "com.unity.render-pipelines.universal": "7.3.1",
    "com.unity.test-framework": "1.1.3",
    "com.unity.textmeshpro": "2.1.1",
    "com.unity.timeline": "1.2.14",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualeffectgraph": "7.3.1",
    "com.unity.xr.interaction.toolkit": "0.9.4-preview",
    "com.unity.xr.legacyinputhelpers": "2.1.4",
    "com.unity.xr.management": "3.2.15",
    "com.unity.xr.oculus": "1.4.3",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by samueljonasson** [comment]
{
	"scopedRegistries": [
{
			"name": "Packages from jillejr",
			"url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
			"scopes": [
				"jillejr"
			]
		},
		{
			"name": "NPM Registry",
			"url": "https://registry.npmjs.org",
			"scopes": [
				"com.mambojambostudios.unity-atoms-core",
				"com.mambojambostudios.unity-atoms-base-atoms",
				"com.mambojambostudios.unity-atoms-fsm",
				"com.mambojambostudios.unity-atoms-mobile",
				"com.mambojambostudios.unity-atoms-mono-hooks",
				"com.mambojambostudios.unity-atoms-tags",
				"com.mambojambostudios.unity-atoms-scene-mgmt",
				"com.mambojambostudios.unity-atoms-ui"
			]
		}
	],
	"dependencies": {

		"jillejr.newtonsoft.json-for-unity": "12.0.301",

		"com.mambojambostudios.unity-atoms-core": "4.3.0",
		"com.mambojambostudios.unity-atoms-base-atoms": "4.3.0",
		"com.mambojambostudios.unity-atoms-mono-hooks": "4.3.0",

		"com.unity.2d.sprite": "1.0.0",
		"com.unity.2d.tilemap": "1.0.0",
		"com.unity.collab-proxy": "1.2.16",
		"com.unity.ide.rider": "1.1.4",
		"com.unity.ide.vscode": "1.2.2",
		"com.unity.postprocessing": "2.3.0",
		"com.unity.probuilder": "4.2.3",
		"com.unity.render-pipelines.universal": "7.3.1",
		"com.unity.test-framework": "1.1.3",
		"com.unity.textmeshpro": "2.1.1",
		"com.unity.timeline": "1.2.14",
		"com.unity.ugui": "1.0.0",
		"com.unity.visualeffectgraph": "7.3.1",
		"com.unity.xr.interaction.toolkit": "0.9.4-preview",
		"com.unity.xr.legacyinputhelpers": "2.1.4",
		"com.unity.xr.management": "3.2.15",
		"com.unity.xr.oculus": "1.4.3",
		"com.unity.modules.ai": "1.0.0",
		"com.unity.modules.androidjni": "1.0.0",
		"com.unity.modules.animation": "1.0.0",
		"com.unity.modules.assetbundle": "1.0.0",
		"com.unity.modules.audio": "1.0.0",
		"com.unity.modules.cloth": "1.0.0",
		"com.unity.modules.director": "1.0.0",
		"com.unity.modules.imageconversion": "1.0.0",
		"com.unity.modules.imgui": "1.0.0",
		"com.unity.modules.jsonserialize": "1.0.0",
		"com.unity.modules.particlesystem": "1.0.0",
		"com.unity.modules.physics": "1.0.0",
		"com.unity.modules.physics2d": "1.0.0",
		"com.unity.modules.screencapture": "1.0.0",
		"com.unity.modules.terrain": "1.0.0",
		"com.unity.modules.terrainphysics": "1.0.0",
		"com.unity.modules.tilemap": "1.0.0",
		"com.unity.modules.ui": "1.0.0",
		"com.unity.modules.uielements": "1.0.0",
		"com.unity.modules.umbra": "1.0.0",
		"com.unity.modules.unityanalytics": "1.0.0",
		"com.unity.modules.unitywebrequest": "1.0.0",
		"com.unity.modules.unitywebrequestassetbundle": "1.0.0",
		"com.unity.modules.unitywebrequestaudio": "1.0.0",
		"com.unity.modules.unitywebrequesttexture": "1.0.0",
		"com.unity.modules.unitywebrequestwww": "1.0.0",
		"com.unity.modules.vehicles": "1.0.0",
		"com.unity.modules.video": "1.0.0",
		"com.unity.modules.vr": "1.0.0",
		"com.unity.modules.wind": "1.0.0",
		"com.unity.modules.xr": "1.0.0"
	}
}

Sorry about the formatting. It gets all messed up and it did not help to insert it as code. It is still valid JSON.

**Comment by samueljonasson** [comment]
Ok I think there is some misunderstanding.  

There is a [/Core/Runtime/Listeners](https://github.com/AdamRamberg/unity-atoms/tree/master/Packages/Core/Runtime/Listeners) in Core.  
They are abstract classes so I assumed that there would be concrete implementations in [/BaseAtoms/Runtime](https://github.com/AdamRamberg/unity-atoms/tree/master/Packages/BaseAtoms/Runtime) but there are none.

Not even on the Github repository so there is most likely nothing wrong with my manifest.  Should there be Listeners in BaseAtoms?

I have a feeling that this issue is an "issue with the user"

**Comment by miikalo** [comment]
I have been using <Type>EventReferenceListeners, however they were earlier simply called <Type>Listeners. I don't remember when that changed.

**Comment by TowerCrow** [comment]
I just assumed they're renamed to Base Event Reference Listener:

https://i.imgur.com/fV2y5a0.png
![image](https://user-images.githubusercontent.com/46613876/96312598-97606780-1014-11eb-860a-319b75917c99.png)

**Comment by samueljonasson** [comment]
That must be it. Although I find the naming a bit misleading.  Sounds like something one would extend. 
But it does explain the "missing" listeners.  Thank you for your input.

**Comment by miikalo** [comment]
Closing because question author is satisfied with the answers.
