### ISSUE TITLE
[BUG] SerializedDictionary Memory Leak

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#204]
**Describe the bug**
Atom Collection SerializeKeys don't clear when the dictionary is cleared. This makes the AtomCollection very intense memory consuming after multiple iterations of the game (big chance of crashing unity if inspected)

**To Reproduce**
1. Make a script that adds elements to an Atom Collection `collectionName.Value.Add(key, value)`
2. Make a script that clears the Atom Collection `collectionName.Value.Clear()`
3. Debug to see that the Atom Collection is actually empty.
4. Observe the atom collection in the inspector after clearing and notice that the keys are still there.

**Expected behavior**
The serialized keys should also be cleared when the dictionary is cleared.

**Environment**
 - Unity Version [e.g. 2019.3]
 - Version of Unity Atoms [e.g. v2.0.0]

**Comment by soraphis** [comment]
https://github.com/AdamRamberg/unity-atoms/blob/canary/Packages/BaseAtoms/Runtime/Collections/SerializableDictionary.cs

the serialized dictionary implementation does not clear the serialized value lists, but only the dictionary, which is populated again after (de)serialization:

https://github.com/AdamRamberg/unity-atoms/blob/canary/Packages/BaseAtoms/Runtime/Collections/SerializableDictionary.cs#L151-L154

**Comment by AdamRamberg** [comment]
Fixed in #218 . Will be included in the next release of Unity Atoms.
