### ISSUE TITLE
[QUESTION] Is there a built-in way to allow a MonoHook to set a variable's value on Awake as an example?

### ISSUE THREAD

**Issue by samueljonasson** [AdamRamberg/unity-atoms#208]
**State your question below**
Is there a built-in way to allow a MonoHook ( or something else ) to set a variable's value on Awake as an example?

**Add any additional information / background**
Let's say that I have a GameObject variable called PlayerGOVariable.  I want to populate this variable at runtime with a player object in the hierachy.  I can of course do this in code but does Atoms come with helpers to allow me to do this in the inspector?
I though I would use the MonoHooks but that does not work.

**Comment by miikalo** [comment]
Hi @samueljonasson , if you tried MonoHooks (I assume OnAwakeHook) could you elaborate what you tried and how did it not work?

**Comment by samueljonasson** [comment]
Hi @miikalo,
Yes, I can.   I was trying to populate a game object variable on runtime without code or extra scriptable objects.  I had hoped that I could drag the OnAwakeHook component onto a game object and then give the component references to the variable and the PlayerGoVariable.  So that is what I tried but, of course, saw that is not how the hook is intended to be used.

Is it correct that I would need to create an Action for this to be possible?

**Comment by nevernotsean** [comment]
@samueljonasson there is a component called SyncGameObjectToVariable which binds a scene GameObject to a GameObjectVariable atom on awake. Try that by using the 'Add Component' button on a gameobject.

**Comment by samueljonasson** [comment]
Nice. Thank you.
