### ISSUE TITLE
[BUG] InvalidCastException: Specified cast is not valid. in FSM

### ISSUE THREAD

**Issue by kamend** [AdamRamberg/unity-atoms#209]
**Describe the bug**
This is driving me crazy! I am trying to use the Finite Machine State Instancer like in the example in Enemy, but a very simple setup gives me an error:

InvalidCastException: Specified cast is not valid.
UnityAtoms.FSM.FiniteStateMachineReference.get_Machine ()

**To Reproduce**

Just use the Atoms examples, drag the Enemy prefab in the Scene, remove the FiniteStateMachineInstancer and add it again, choosing the EnemyStateMachineBase as Base, drag the FinishteStateMachineInstancer to the EnemyMovement script in the Enemy State slot. Once you run the app you will get the Invalid Cast error, this is exactly the same setup as in the initial Prefab version, but it just does not work. But it works in the prefab, if we do not change anything. Is there maybe some bug in the Editor scripts when you add the FiniteStateMachine? I really could not figure this out.

**Environment**
 - OS: MacOS
 - Unity Version 2020.1.11f
 - Version of Unity Atoms: latest

**Comment by kamend** [comment]
Here is something else I noticed, this is a second Finite State Machine Instancer I added to the Enemy prefab. Notice how the In Memory Copy of the second one I added is of String type. For some reason the Fsm Base value is disregarded and the In Memory Copy is not created as an instance of it. The weird thing is that the original FSMInstancer works as intended and it is setup the same way, it is just already added to the prefab. Probably some Unity bug?

<img width="649" alt="Screen Shot 2020-11-13 at 17 43 03" src="https://user-images.githubusercontent.com/462951/99090866-ccda7f80-25d7-11eb-87c7-a31f2bd2aa84.png">

**Comment by kamend** [comment]
Ok, I found where the error comes from. Its in AtomBaseVariableInstancer!

In:

        private void OnEnable()
        {
            Debug.Log(_base);
            Debug.Log(Base);
            if (_base == null)
            {
                _inMemoryCopy = ScriptableObject.CreateInstance<V>();
            }
            else
            {
                _inMemoryCopy = Instantiate(Base);
            }
            ImplSpecificSetup();
        }

You check if _base is null, but in the case of FiniteStateMachineInstancer it will always be null, because the overriden variable is Base, so the fix is to check if Base is null, not _base in order everything to work. I guess the Enemy prefab is working, because in an older version of Atoms, you have provided a _base variable. Now, this variable is hidden in the FiniteStateMachineInstancerEditor script, so it's always null.

**Comment by AdamRamberg** [comment]
Hi @kamend! Thanks for submitting this issue. Great catch in your last post. I will submit a fix for this which will be included in the next release of Atoms.

**Comment by AdamRamberg** [comment]
Fixed in canary. Will be included in next release of Unity Atoms. Closing the issue.
