### ISSUE TITLE
Generator to create new Atoms (classes)

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#21]
It would be really nice to have a generator that creates new atoms classes for you, to reduce the amount of boilerplate code to be written. It should be possible to choose what to generate (Variable, EventListener, Constant, etc), what to name it and what types to use. 

Not sure what techniques to use. Have worked with Yeoman / EJS before, but not sure if it's a good fit for Unity / C# (is it possible to run from the inspector if it's a node module for example?). Maybe do some custom templating?

**Comment by soraphis** [comment]
in my fork, i already added a code generator

https://github.com/soraphis/unity-atoms/blob/stable/Editor/Dev/CodeGenerator.cs

this is ignored for package manager, and it uses my refactored folder structure, but you might find it helpfull

**Comment by AdamRamberg** [comment]
@soraphis That is great! Would you mind creating a pull request for this? ⭐️ 

Think it shouldn't be ignored by the package manager though. It should be possible for users of Unity Atoms to easily generate their own atoms.

**Comment by AdamRamberg** [comment]
Initial generator has been mereged from @soraphis branch. Closing this one and will create a new issue for future improvements.
