### ISSUE TITLE
[BUG] Instance variables do not trigger "Trigger event on OnEnable" -> "Changed"

### ISSUE THREAD

**Issue by archer3cl** [AdamRamberg/unity-atoms#210]
**Describe the bug**
Creating an instance variable does not trigger "Trigger event on OnEnable" -> "Changed"

**To Reproduce**
-> Create an int variable, tick "Trigger Event on OnEnable" - "Changed"
-> On gameobject create an "Int Variable Instancer" and assign the created int variable
-> Create an "Int Event Reference Listener" and assign the previous variable instancer in "Event Reference"
-> Register an event
-> Click Play
-> The event is not fired OnEnable

**Expected behavior**
Instance variables should trigger "Trigger event on OnEnable" if "Changed" or "ChangedWithHistory" are checked

**Environment**
 - OS: Windows
 - Unity Version 2020.1.9f1
 - Version of Unity Atoms 4.3.0

**Additional context**
Attached demo project with demonstration
[Examples.zip](https://github.com/AdamRamberg/unity-atoms/files/5573419/Examples.zip)

**Comment by AdamRamberg** [comment]
Fixed in #220. Will be included in the next release of Unity Atoms.
