### ISSUE TITLE
[FEATURE] (canary) Move "Atoms Search" under "Unity Atoms" in the "Create" context menu

### ISSUE THREAD

**Issue by miikalo** [AdamRamberg/unity-atoms#213]
**Is your feature request related to a problem? Please describe.**
The Unity Atoms and Atoms Search belong together but have two separate entries in Create context menu:

![image](https://user-images.githubusercontent.com/1841625/101826100-d13e7d80-3b2e-11eb-8367-9c37de5d6c4b.png)

**Describe the solution you'd like**
The Atoms Search should be moved under Unity Atoms to avoid cluttering the Create context menu and renamed to Search (Atoms would be implied if the option is under Unity Atoms). In my opinion packages should avoid cluttering the context menus and create only one main level entry.

**Describe alternatives you've considered**
Remove older context menu "Unity Atoms" altogether as "Atoms Search" is also browseable.

**Additional context**
Bonus: Make the hotkey Alt+1 configurable from the Unity Atoms settings menu to avoid hotkey conflicts.

**Comment by AdamRamberg** [comment]
Fixed in canary. Will be included in next release of Unity Atoms. Closing the issue.
