### ISSUE TITLE
Trigger GameEvents from the inspector

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#22]
Create an editor script to make it possible to trigger GameEvents from the Unity Inspector. Probably best to create a generic class that gets extended for each GameEvent type.

**Comment by rakkarage** [comment]
one easy way to implement this is to add [ContextMenu("Raise")] to the event... then you can right click and select menu item to execute in editor

this unity addon improves the editor experience for lists and ScriptableObjects and shows buttons for ContextMenus

https://github.com/SubjectNerd-Unity/ReorderableInspector

**Comment by AdamRamberg** [comment]
Thanks @rakkarage ! Using ContextMenu sounds really cool! Actually didn't know about that. 

I think the easiest approach though would be to in the [GameEventEditor](https://github.com/AdamRamberg/unity-atoms/blob/master/Source/Editor/GameEventEditor.cs) support passing your own value (from the inspector). Would at the same time be pretty rad to support rewrite it using the Unity's new UIElement approach to writing editor UI.

**Comment by AdamRamberg** [comment]
Fixed in 6693a27d2da2ff691752560e9619863ea7a4e554
