### ISSUE TITLE
Create events as delegates or actions

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#24]
Is there any special reason behind the events having to implement an interface? Doesnt this even makes it weirder if you want to listen for 2 events of the same type in a single class?

**Comment by soraphis** [comment]
shouldn't be that much of a problem.
I've implemented it in my fork: https://github.com/soraphis/unity-atoms/commit/20ac23efc094d967939e4092535815dab9fc3b5d

using C# events. The important part is to ensure that events are unregistered. this could be a problem within the editor, but I think my usage of 'OnAfterDeserialize' should fix this

**Comment by AdamRamberg** [comment]
First of all, the [IGameEvent](https://github.com/AdamRamberg/unity-atoms/blob/master/Source/Base/IGameEvent.cs) interface is totally unnecessary. It's a left over from when I started the project. Will remove it in a future commit. 

Regarding the IGameEventListener, that is a different issue. I have actually tried the same approach as @soraphis is doing in this fork. However, this did hurt performance way too much and it's unfortunately not a viable option (even though it is much more elegant code-wise). Maybe I did something wrong and it's worth a second try? Or maybe there are any other approaches to this problem (can't think of any now though)? I agree with you @mutmedia that it is really awkward when using 2 events of the same type in the same class.

**Comment by AdamRamberg** [comment]
Removed IGameEvent in 16ab226

**Comment by soraphis** [comment]
> However, this did hurt performance way too much and it's unfortunately not a viable option 

oO thats interesting.
i just looked a bit around and found this article: https://jacksondunstan.com/articles/3043

first: I would not have thought that events would get worse with repeaded use within a short timespan, but I think the conclusion of this article is pretty fitting.

> Now that we’ve established which is faster—interfaces—the question becomes: should you bother? Interfaces are definitely more work to set up, harder to read, more error-prone, and more difficult to integrate into your code.
> Say your game had a thousand callbacks per frame. That’d be a lot of callbacks, but still 100,000 times less than this article’s test results show. Even in the slowest case—events with multiple callback functions—you’d only be using 0.00749 milliseconds to call all the callbacks.

**Comment by AdamRamberg** [comment]
@soraphis Will read the article when I get time this weekend! 

I could definitely try doing the move again and then try it in my current game project. If the performance / framerate is not hurt then great, but if it is noticeable it's unfortunately a no go.

**Comment by AdamRamberg** [comment]
GameEvents are now using C# events since commit d551947c13728ab9a754ced28a92e7d3e8a24b62 (branch canary). Seems like no noticeable performance hit when implementing it. Not sure why I got such a performance hit last time (probably did something stupid in the implementation). 

Thanks for the input everyone! Closing the issue.
