### ISSUE TITLE
Variable transformers, eg. Clamp Value

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#27]
For Variables, set a ShouldUpdate "hook" that you query before you update the value. Eg: 
`
        public bool SetValue(T value)
        {
if (!AreEqual(this.value, value) && (ShouldUpdate == null  || (ShouldUpdate != null && ShouldUpdate(T newValue, T currentValue, T oldValue))))
            {
                 // Set value
            }
        }
`
This makes it possible to add your custom logic to your variables, for example "clamp value" - to clamp the value between a min and a max. In this feature it is also included to create the "clamp value" hook.

**Comment by soraphis** [comment]
instead of "hooks" (which sounds to me like 'event system'), it would be possible to make variables contain a list of "value preprocessors".

when a variable is set to a new value, the new value is modified by those preprocessors first.

an example implementation to demonstrate this:

```Csharp
public abstract class ValuePreProcessor<T>{
    public abstract T Process(T value);
}

public abstract class ScriptableVariable<T> : ScriptableObject{

    private T value;
    public T Value{
        get{ return value; }
        set{
            var val = value;
            for(int i = 0; i < preProcessors.Length; ++i){
                val = preProcessors.Process(val);
            }
            this.value = val;
        }
    }

    public ValuePreProcessor<T>[] preProcessors;

}

public class FloatVariable : ScriptableVariable<float>{}

public class ClampPreProcess : ValuePreProcessor<float>{
    public FloatReference minValue;
    public FloatReference maxValue;

    public override float Process(float value){
        return Mathf.Clamp(value, minValue.Value, maxValue.Value);
    }
}
```

**Comment by jeffcampbellmakesgames** [comment]
I think a simpler implementation of this for numeric values would be to add new fields on each closed numeric scriptable variable type  for asserting that the value should be constrained, the min/max of the range, and then `SetValue` would use these internally when setting the value to clamp it to the desired range. It would require a small amount of additional code per type, but this would be mostly a copy-paste with maybe some slight variation. Adding another OOP level to `SetValue` for processing simple value types seems like overkill.

**Comment by AdamRamberg** [comment]
I really like @soraphis solution - it's flexible and extendible. ValuePreProcessor should be an array of GameFunctions though like this: 
`
      public abstract class ScriptableObjectVariable<T, E1, E2, GF> : ScriptableObjectVariableBase<T>,
        IWithOldValue<T>,
        ISerializationCallbackReceiver
        where E1 : GameEvent<T>
        where E2 : GameEvent<T, T>
       where GF : GameFunction<T, T>
    {
         ...
         [SerializeField]
         private GF[] _preProcessors;
         ...
    }
`

**Comment by AdamRamberg** [comment]
I'm updating the issue since it's quite old. 

**My thoughts going forward**
I still think that the preprocessor solution would be really nice, although I think the name should be `_valueTransformers` instead of `_preProcessors`. I think that the implementation should look something like this: 
```
public abstract class AtomVariable<T, E1, E2, F> : AtomBaseVariable<T>,
    ISerializationCallbackReceiver
    where E1 : AtomEvent<T>
    where E2 : AtomEvent<T, T>
    where F : AtomFunction<T, T>
{
    [SerializeField]
     private F[] _valueTransformers;
}
```
We should then loop through the transformers before we apply the value. 

I would be really appreciate someone making a PR on this. Make sure to read the [guidelines](https://github.com/AdamRamberg/unity-atoms/blob/canary/CONTRIBUTING.md) before starting + assign yourself (or ask me) to the issue. Also make sure to update the templates for the generator and also regenerate all the existing Atoms.

**Comment by AdamRamberg** [comment]
Added in #93
