### ISSUE TITLE
Initial value for variables

### ISSUE THREAD

**Issue by mattdevelops** [AdamRamberg/unity-atoms#3]
Wouldn't it be quite convenient if it had default variables that reset each time on `OnEnable` or somewhere else ? Or am I missing some design philosophy here ? :)

**Comment by AdamRamberg** [comment]
Good question! I initially did this, but OnEnable is only called when the game starts and not when a new scene is loaded. I therefore choose to set initial state explicitly in each scene using the MonoHook OnStartHook and one of the SetVariable Game Actions like explained in the medium blog post I did (go to the MonoHooks section): https://medium.com/@adamramberg/unity-atoms-tiny-modular-pieces-utilizing-the-power-of-scriptable-objects-e8add1b95201 

After the reasoning above, do you still think it is necessary to have a default value on Variables?

**Comment by mattdevelops** [comment]
Ahh makes total sense, forgot about the SO lifecycle. :)

**Comment by rakkarage** [comment]
https://docs.unity3d.com/ScriptReference/MonoBehaviour.Reset.html

**Comment by AdamRamberg** [comment]
@rakkarage Not really sure if that is a solution for this particular problem. However, it might be great for convenience when working with the ScriptableObjects in the editor.
