### ISSUE TITLE
ScriptableObjectList should implement IList

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#33]
Is there any special reason why ScriptableObjectList doesnt implement any Enumerable interfaces?
ICollection can be implemented basically for free

**Comment by mutmedia** [comment]
Tried implementing myself and figured that IList is actually the best alternative

**Comment by AdamRamberg** [comment]
Have just not be done, no reason really. Would gladly accept a PR to the canary branch ⭐️
