### ISSUE TITLE
Clean up `[AddComponent]` and `[CreateAssetMenu]` usage

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [AdamRamberg/unity-atoms#36]
### Summary
Making it easier for users to find and add the appropriate component or create the appropriate `ScriptableObject` derived unity-atom asset can make this library much easier for new users. There is some consistency with the context menu creation for SO assets, but I think some reorganization could help there as well. There is a bit more cleanup to do in order to get these AddComponent menus more organized. 

![image](https://user-images.githubusercontent.com/1663648/56089640-51ae6600-5e96-11e9-95f0-ae23216e16f4.png)

As of the latest on canary, these seem to be mostly organized around the type they revolve around versus the type of thing they are. This can lead to making these menus less navigable for a user if there is growth of atoms revolving around a particular type.

For example, everything dealing with an `GameObject` value is organized for the context menu into a single scope including actions, events, variables, lists, etc... Right now as far as I can see there is only a single `GameObject` action of type `GetUnusedGameObject`, but presumably this list could grow to be very large as the number of actions/events revolving around `GameObject`(s) is subject to a lot of growth. 

![image](https://user-images.githubusercontent.com/1663648/56089701-427be800-5e97-11e9-84b2-ddfc0317991f.png)

For both SO asset creation and AddComponent menus, I believe a more helpful structure would be to organize these into the type of thing they are versus what they revolve around or use. Instead of a structure looking like this:

* Unity Atoms
    * Int
    * Vector3
    * GameObject
        * Variable
        * Event
        * List
        * GameObjectAction1
        * GameObjectAction2
        * GameObjectAction3
        * ...

you would have something that looked like this:

* Unity Atoms
    * Variable
        * Int
        * Vector3
        * GameObject
    * List
    * Event
    * Conditional
    * Action
        * GameObject
            * GameObjectAction1
            * GameObjectAction2
            * GameObjectAction3

This is also more in-line with the UX for other popular game development tools like [Bolt](https://ludiq.io/bolt) or [PlayMaker](http://hutonggames.com/index.html) and can lead to a more consistent development experience and quicker onboarding for new users.

![image](https://user-images.githubusercontent.com/1663648/56089941-d56a5180-5e9a-11e9-8873-8e056bf76d0c.png)

![image](https://user-images.githubusercontent.com/1663648/56089947-db603280-5e9a-11e9-8f9c-d4a3f5992c93.png)

![image](https://user-images.githubusercontent.com/1663648/56089917-a05dff00-5e9a-11e9-8d5b-e924bb727e23.png)

Making these changes would not result in any breaking API changes for end-users as these affect the Unity Editor UX only and would be a general UX improvement with little downsides.

**Comment by AdamRamberg** [comment]
The library was actually in the beginning following the pattern that you propose. After having tried both approaches I actually believe that you are right, it makes more sense to group on its function rather than on what type it is. 

When doing this change the folder structure in the project should resemble the UI changes. That said, this becomes a pretty large change. I think this is something we definitely should do, but think we should wait a little before doing it.

**Comment by mbryne** [comment]
+1 for organising by Type of thing rather than underlying data type, 

So Unity Atoms > Variable > Int / Vector3 etc

**Comment by AdamRamberg** [comment]
Implemented in b33b2b8a72c75aaf096455baf39f296f38b28aca and in 0e896f160c8e02d38d3105eb4782952e2d76c713.
