### ISSUE TITLE
Create SceneConstant Atom

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [AdamRamberg/unity-atoms#37]
### Summary
Something that would be useful for developers would be an Atom revolving around a `SceneAsset`. Ideally it does not keep a reference to a `SceneAsset` itself since it is an editor-only type, but instead serializes its full path and name only so that at runtime a user could load a scene using that serialized name or path value.

This would have a custom inspector/property drawer so that a user can assign a `SceneAsset` directly to the Atom or ping the currently referenced instance in the Project view, but would only assign its name and path to serialized fields.

The benefit of this versus a `StringConstant` or  `StringVariable` is that this would offer a better UX and stronger validation of the values. There is a lack of validation that a general-purpose type offers that this more specific type could address. For example, the Atom itself could leverage `OnValidate` to assert that the name/path values should not be blank, custom methods to indicate that the name/path resolves to a valid scene in the build settings, and the custom inspector could also warn the user if the referenced `SceneAsset` was not in the build settings or asset bundle.

**Comment by AdamRamberg** [comment]
Closed in #40
