### ISSUE TITLE
Not serialized in the inspector

### ISSUE THREAD

**Issue by 0x16e8bea** [AdamRamberg/unity-atoms#4]
Serialized fields do not show up in the inspector for some reason. At the moment, the only way to inspect and assign values is to activate debug mode.

**Comment by 0x16e8bea** [comment]
To be specific, we tried to add the files to our own project in our team, and the issue only occurs then. It seems to work fine when we open unity-atoms as a standalone project.

**Comment by 0x16e8bea** [comment]
Closing this issue. It was caused by another Unity plugin.

**Comment by AdamRamberg** [comment]
Great that you found a solution :)
