### ISSUE TITLE
Name Listener Components based on Specified Event Name

### ISSUE THREAD

**Issue by ricke44654** [AdamRamberg/unity-atoms#41]
Rename Game Listener components in the Inspector based on the specified event for which it is listening.  Currently, if you have several Game Listener components on a scene object / prefab, you may have several listeners with the same generic name (e.g. Game Object Listener) and it makes it harder to find which listener you need in the Inspector.

**Comment by AdamRamberg** [comment]
Thanks for submitting an issue! 

Think that it's a great idea to indicate in some way what Game Event is attached to a Game Listener. Don't think it should be by name though. Have to think about other possibilities 🤔

**Comment by AdamRamberg** [comment]
In cdbdce73293adc8e3b3b3054a327e22b4900b624 I did add a none generic base class for all Listeners including a field called "Developer Description". I think this will suffice for your needs. Use the latest version of canary in order to try it out. Closing the issue.
