### ISSUE TITLE
Unable to register event response for EventListeners

### ISSUE THREAD

**Issue by bgordley** [AdamRamberg/unity-atoms#43]
While attempting to register a function of a custom script as an event response for a VoidEvent I am not able to select a function. The function itself takes no variables, is public, and returns void. 

Here is what I see when I try to register the custom script.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/7117601/57971518-17782e80-7944-11e9-99d8-868eedbf2d4c.png">

Two things to note.
- Custom script derives from MonoBehaviour
- I am using Unity for macOS

**Comment by AdamRamberg** [comment]
Hello @bgordley! 

How are you assigning the CollectSandTile script? It's not possible assign just the script to the Unity Event Response, instead you need to have the CollectSandTile script attached to a GameObject and then assign the GameObject to the handler. Let me know if that solves your issue :)

**Comment by bgordley** [comment]
Thanks @AdamRamberg !

That makes a lot of sense now that I have it working. I think it was confusing because the UnityEventResponse can be anything that derives from Object. Is there a reason it would not derive from GameObject?
