### ISSUE TITLE
Unity Atoms unable to find UnityEngine.UI

### ISSUE THREAD

**Issue by CapitanLiteral** [AdamRamberg/unity-atoms#45]
I'm using 2019.3.0a4 version

When I add atoms on package manager this i what I see on my console, any Idea of what could be happening?

[CompilerError] The type or namespace name 'UI' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Compiler Error at Library\PackageCache\com.mambojambostudios.unity-atoms@163a216fc14abf9b9f6014ec77ea1fe31c547c4f\Source\MonoHooks\OnButtonClickHook.cs:2 column 19
1:   using UnityEngine;
-->2:   using UnityEngine.UI;
4:   namespace UnityAtoms

[CompilerError] The type or namespace name 'EventSystems' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Compiler Error at Library\PackageCache\com.mambojambostudios.unity-atoms@163a216fc14abf9b9f6014ec77ea1fe31c547c4f\Source\MonoHooks\OnPointerDownHook.cs:2 column 19
1:   using UnityEngine;
-->2:   using UnityEngine.EventSystems;
4:   namespace UnityAtoms

[CompilerError] The type or namespace name 'IPointerDownHandler' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Library\PackageCache\com.mambojambostudios.unity-atoms@163a216fc14abf9b9f6014ec77ea1fe31c547c4f\Source\MonoHooks\OnPointerDownHook.cs:7 column 55
5:   {
6:       [AddComponentMenu("Unity Atoms/Hooks/On Pointer Down")]
-->7:       public sealed class OnPointerDownHook : VoidHook, IPointerDownHandler
8:       {
9:           public void OnPointerDown(PointerEventData eventData)

[CompilerError] The type or namespace name 'PointerEventData' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Library\PackageCache\com.mambojambostudios.unity-atoms@163a216fc14abf9b9f6014ec77ea1fe31c547c4f\Source\MonoHooks\OnPointerDownHook.cs:9 column 35
7:   public sealed class OnPointerDownHook : VoidHook, IPointerDownHandler
8:   {
-->9:       public void OnPointerDown(PointerEventData eventData)
10:       {
11:           OnHook(new Void());

[CompilerError] The type or namespace name 'Button' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Library\PackageCache\com.mambojambostudios.unity-atoms@163a216fc14abf9b9f6014ec77ea1fe31c547c4f\Source\MonoHooks\OnButtonClickHook.cs:7 column 30
5:   {
6:       [AddComponentMenu("Unity Atoms/Hooks/On Button Click")]
-->7:       [RequireComponent(typeof(Button))]
8:       public sealed class OnButtonClickHook : VoidHook
9:       {

**Comment by soraphis** [comment]
> When I add atoms on package manager this i what I see on my console, any Idea of what could be happening?

You're using an alpha version of unity. for 2019.2+ unity separates the UI components into a different assembly. Since there isn't a 2019.2+ branch for unity atoms (for now) the dependencies are not reflected by the assembly definition.

I'll look later into that, and will make a PR.

**Comment by soraphis** [comment]
@AdamRamberg I've looked a bit into this.
Unity is separating the UI for the sake of a modular engine.

But we've got AtomicUI and MonoHooks depending on UI.

The options for 2019.2+ would be to either:

- Create a new package for UnityAtoms.UI which depends on Unity.ugui
- Make the whole UnityAtoms depending on Unity.ugui

I personally would favor the first option, because when UIElements gets runtime support, there may appear games that don't use Unity.ugui.

but as a simple fix for now, I've added Unity.ugui to the UnityAtoms assembly definition 

see PR #46

**Comment by AdamRamberg** [comment]
Fixed in PR #46, closing the issue! 

Like mentioned in the comments of PR #46, I will create separate packages for Unity Atoms UI, Tags, etc. After that I will add the assembly definition to Unity Atoms UI instead of to the full project.
