### ISSUE TITLE
No Int Int listener?

### ISSUE THREAD

**Issue by grofit** [AdamRamberg/unity-atoms#56]
Was just trying to subscribe to an int int event in the editor but that listener doesnt seem to exist, is there a reason why I shouldnt have an int int listener? or is it just an oversight

**Comment by soraphis** [comment]
I'm pretty sure this is an oversight. probably because Ints and Floats where created before the Generation stuff was written and before x2 events/listeners where introduced.

There are missing x2 listeners for:

Bool, Collider2D (has no x2 event, too), Color, Float, GameObject, Int, Vector2, Vector3, Void.

There are x2 listeners:

String, TouchUserInput

____

It should be possible to write a Test that covers, that for each Event-Type there is also an Listener-Type

**Comment by AdamRamberg** [comment]
Thanks for submitting the issue! 

This has been overlooked. Will be continue working on the generator this weekend, so all the missing ones will be added to the canary branch. 

Would you consider it useful if the generator was able to generate atoms that are of different types? Eg. IntStringListener or FloatIntEvent?

**Comment by soraphis** [comment]
> Would you consider it useful if the generator was able to generate atoms that are of different types? Eg. IntStringListener or FloatIntEvent?

since those x2 events are usually used for "ChangedWithHistory"-events on a variable, and because there are a lot of combinations possible (IntString, StringInt ?) and if needed those classes can be created by the library user for the types needed. I'd vote against adding all those combinations

**Comment by AdamRamberg** [comment]
Maybe I was unclear in my question :) I totally agree that we should not add all of them to the project, however do we think it would be helpful to add the possibility to be able to generate those via the code generator when needed?

**Comment by AdamRamberg** [comment]
IntIntListener was added in cb200087601b162cb9ac5e8a928f36ca31a5b910

**Comment by grofit** [comment]
Hey, so sorry I didnt respond here, for some reason I didnt get notifications of this, im happy with those bits just being added but if you wish to make it more flexible in the future I cannot see a downside to that.

**Comment by AdamRamberg** [comment]
@grofit Thansk! Will create a new issue regarding expanding the generator!
