### ISSUE TITLE
Why AtomReference does not use AtomBaseVariable as Constant?

### ISSUE THREAD

**Issue by icaro56** [AdamRamberg/unity-atoms#58]
Why AtomReference does not use AtomBaseVariable as Constant?

e. g. IntReference has a int and a IntVariable, but could be a IntConstant and a IntVariable.

**Comment by soraphis** [comment]
it is such that you can provide your level designers the oportunity to put a fix number in there without the need of creating an asset.

note: IntConstant derives from AtomBaseVariable<int> also IntVariable does so. **this means:** _you can put a AtomConstant into the AtomVariable option of an AtomReference_

**Comment by icaro56** [comment]
Ok, thank you by explanation.

**Comment by icaro56** [comment]
But by some reason the StringConstant is not aceptable on StringVariable field when I use the StringReference

**Comment by soraphis** [comment]
Ah okay i see.

@AdamRamberg 

References use "hardcoded" the variable like here: `    public class StringReference : ScriptableObjectReference<string, StringVariable, StringEvent, StringStringEvent> { }
` 

"StringVariable" in the generic argument. I think this "should" be `ScriptableObjectVariableBase<string>` but I'm unsure whether or not this would still be serializable. 
I'll try to test it this evening, but maybe you're faster than I am

**Comment by icaro56** [comment]
I understand. Thank you. Your plugin is fine! I am using the canary version. May the force be with you!

**Comment by soraphis** [comment]
> "StringVariable" in the generic argument. I think this "should" be ScriptableObjectVariableBase<string> 1 but I'm unsure whether or not this would still be serializable.

okay, you can't use a generic argument at this position - it will not serialize anymore.
thats a bummer .

we could add a third option to reference to also allow a AtomConstants option.

when 2020.1 hits this can be restructured altogether with SerializeReference

**Comment by AdamRamberg** [comment]
@icaro56 I added the option to use a Constant in Atom References in commit 299dc195e2c9c7dcc425bf56c776c6cf6262500e. Use the latest canary version if you want to use it.
