### ISSUE TITLE
Do you want us to create a Unity Atoms Slack / Discord / Spectrum channel?

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#59]
Like stated above, would you like us to create a Slack, Spectrum or Discord (or something else) channel to be able to communicate more effectively? Please add a thumbs up (👍) to the option that you prefer below 👇 

If you want something other then Slack, Spectrum or Discord create a new comment with that option.

**Comment by AdamRamberg** [comment]
Slack

**Comment by AdamRamberg** [comment]
Discord

**Comment by AdamRamberg** [comment]
Spectrum

**Comment by AdamRamberg** [comment]
I don't think it will add any value to the project

**Comment by soraphis** [comment]
My thoughts:
Basically everyone nowadays has Discord, while slack is nice it would probably require more people to create new accouns. (while i like the slack formatting features more than discords)
i didn't knew spectrum before, but i think it could work great.

**Comment by SomePlayer** [comment]
What is Slack?
What is Spectrum?
I vote Discord

**Comment by mutmedia** [comment]
This would be cool!
Even if I still havent contributed much, this tool is basically what all my current unity projects' been using, so it would be awesome to have some faster communication  =)

**Comment by markcastle** [comment]
I haven't contributed yet much either but have recently converted a game I'm working on to using UnityAtoms and absolutely love it. Happy with any communication medium and also Gitter.

**Comment by AdamRamberg** [comment]
Thanks to everyone for the input! Just created a Discord channel for us. Come and join me, it's way too lonely right now :) 

https://discord.gg/W4yd7E7
