### ISSUE TITLE
[QUESTION] Demo Scene Missing Healthbar.HealthChanged

### ISSUE THREAD

**Issue by SomePlayer** [AdamRamberg/unity-atoms#62]
**State your question below**
In the demo scene. HealthListener is missing HealthBar.HealthChanged
However, when I "fix" it, I am now required to give a static value. And the health bar no longer works. 

How is it setup to feed the HealthBar.HealthChanged a dynamic variable?

**Add any additional information / background**
Screen shot of the missing state https://snipboard.io/LWk0KG.jpg
Also the health bar needs to be assigned an source image, as its also missing

**Comment by AdamRamberg** [comment]
Definitely related to #63. What version of Unity are you rinning?

**Comment by soraphis** [comment]
> What version of Unity are you running?

from the screenshot its 2019.3.0 beta 7

**Comment by AdamRamberg** [comment]
Closing. Fixed on Unity's side.
