### ISSUE TITLE
What changes might cause this missing dynamic method?

### ISSUE THREAD

**Issue by P-Stringer** [AdamRamberg/unity-atoms#63]
Hi Adam,

Every now and then my event listeners are breaking and I'm unable to setup using dynamic values. Previous dynamic listeners continue to work but the inspector shows the following:

![image](https://user-images.githubusercontent.com/1236686/67082682-8ecf1a00-f191-11e9-99e5-73d09d686cc9.png)

The missing `Actor.TargetAllAbilities` is still present on the game object. Like I say it continues to work too but that might just be because it's not doing a clean build. 

Any ideas? I've raised it as a question rather than a bug due to the fact I'm pretty new to Atoms and relatively new to Unity as a whole - so it might just be me being stupid!

Thanks.

**Comment by P-Stringer** [comment]
May actually be related to a Unity bug - https://issuetracker.unity3d.com/issues/events-generated-by-the-player-input-component-do-not-have-callbackcontext-set-as-their-parameter-type?page=2#comments 

Will investigate.

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! First of all, this is related to #62.

> May actually be related to a Unity bug - https://issuetracker.unity3d.com/issues/events-generated-by-the-player-input-component-do-not-have-callbackcontext-set-as-their-parameter-type?page=2#comments
> 
> Will investigate.

Yep, you are probably right. What version of Unity are you running and what OS? The reason I think this is related to the Unity bug you are linking is that it works just fine for me in Unity 2019.1.0f2.

Another question, is this happening after you have done something in particular or is it just at random?

**Comment by P-Stringer** [comment]
I'm running 2019.2.9f1 on Mac OS Catalina. I can't quite pinpoint the moment it breaks but feel like it might be after importing new scripts I'm creating through Visual Studio. But, that's just a guess - for the most part it seems random. 

I tried updating to the 2019..3.0b7 beta the other day but that created problems else where not related to atoms! For now I'm just using the workaround some posted on the issue tracker.

> Set up the event as normal using static parameter approach them switch to inspector to debug mode and set the event's ”Mode” to ”Event defined”.
> It'll show as ”missing” on return to ”non-debug” mode but it still works.

**Comment by AdamRamberg** [comment]
Closing. Has been fixed on Unity's side. Reopen if you still have problems regarding this.
