### ISSUE TITLE
"Name of new item" text box shows up for all Variables in a list

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#65]
**Description**
If I have multiple unassignes Variables in a list (of serializable classes), when I click to create a new variable, the "Name of new item" text box shows up fot all unassigned variables in the list

Note: When you finally press create, this bug does not create a variable for all the objects, just the one you initially selected for creation, so the impact is very minor 

**To Reproduce**
1. Create a serializable class with a *Variable field
```cs
[Serializable]
public class ClassWithVariable 
{
  // [...]
  FloatVariable var;
  // [...]
}
```
2. Create a List of that class in an MonoBehaviour
```cs
public class MonoBehaviourWithListOfClass : MonoBehaviour
{
  // [...]
  public List<ClassWithVariable> objectsWithVariables;
  // [...]
}
```
3. Add that Behaviour to a game object, some objects to the list, and click on create for one of the variables.
4. Notice that the text box for creating a new variable is showing up for all of the objects in the list

**Expected behavior**
The text box should show up only for the variable being created

**Screenshots**
![image](https://user-images.githubusercontent.com/4412564/67153530-e065ca80-f29f-11e9-9a2f-689720b32ac4.png)

Note that all the variables has "asdfa" with the checkbox and the x opened beside it

**Environment**
 - OS: Windows 10
 - Unity Version 2019.1.13
 - Version of Unity Atoms v2.0.0

**Comment by AdamRamberg** [comment]
Thanks for submitting the issue! 

Apparently, it is not possible to store member variables in PropertyDrawers for each instance. Just committed a fix for this in 0ad40a67d446c6dea3e510a84639c79099978847. Closing the issue.
