### ISSUE TITLE
Selecting Multiple Objects with a same type of event overrides all objects events with the same one

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#68]
**Describe the bug**
If you create multiplie game objects with a common event listener type, selecting all of them makes the event they are listening to be the same as the last selected object (overriding each objects events)

**To Reproduce**
1. Create 2 or more game objects with a same type of event listener (I used Int Listener), each with it's own event (IntEventA and IntEventB in my example)
![image](https://user-images.githubusercontent.com/4412564/67174792-4cb3fd00-f378-11e9-880a-11bdb6516ed4.png)
![image](https://user-images.githubusercontent.com/4412564/67174801-55a4ce80-f378-11e9-826a-9d1c470ab811.png)
2. Select both game objects (note that the event field is actually populated with a value, IntEventB, when it should probably be '-', the symbol for different values)
![image](https://user-images.githubusercontent.com/4412564/67174844-7b31d800-f378-11e9-80f3-379c29236734.png)
3. Deselect the objects and note that all of them now are using the same event value (in my case, Game Object A is using IntEventB)
![image](https://user-images.githubusercontent.com/4412564/67174850-82f17c80-f378-11e9-8304-9a5ee1725f22.png)

**Expected behavior**
Selecting multiple objects should not cause any modifications at all in the game objects

**Environment**
 - OS: Windows 10
 - Unity Version 2019.1.13
 - Version of Unity Atoms v2.0.0

**Comment by AdamRamberg** [comment]
Thanks for submitting this bug! I made a work around in 9cb9a0de208b0c59c49ac283136db04b3d3850ae to disallow multiobject editing. However, I will keep this open and look into a more permanent solution.

**Comment by AdamRamberg** [comment]
The best way to handle this (that I've found) is to fallback to default drawer when one is multi editing objects. Implemented that in b8c3dc668fdcc4237ca4b0400c95fc285e4ef668. Closing the issue.
