### ISSUE TITLE
[FEATURE][PROPOSAL] AtomCollections

### ISSUE THREAD

**Issue by soraphis** [AdamRamberg/unity-atoms#71]
**Is your feature request related to a problem? Please describe.**
The want to group many UnityAtomVariables together, for more structure.

(Possible other use cases, as ViewModel for a View in an MVVM like pattern (UI stuff).

**Describe the solution you'd like**
The possibility to create a "AtomVariableCollection" asset where you can drag-and-drop your atoms as sub-assets into.

![image](https://user-images.githubusercontent.com/3066582/67988216-97aef980-fc2f-11e9-9d72-b327d90a6c24.png)

**This is an Proposal**
Discussion is encouraged. Possible Use-Cases, Features to include.

**Comment by sampaiodias** [comment]
This would be super useful if users could put names on the fields instead of an array. We could access the variables by using collection.Get("Character") or something like that instead of collections.atoms[1]

**Comment by AdamRamberg** [comment]
Really nice feature! 👌 

@sampaiodias I agree that the getting Atoms by a specified key would be neat. I assume you mean that `Get` would return the value of the Variable right? Furthermore, I think this could be pretty tricky to implement though without boxing and / or using reflection due to that we don't know if its a reference or a value type when casting (maybe my knowledge here in this eara is too limited though). That said, would love a solution for this. 

@sampaiodias JSON serialization / deserialization also sounds neat!

**Comment by sampaiodias** [comment]
Maybe it would help if the AtomCollection had an array of AtomCollectionItem instead of AtomVariable or something like that.

```csharp
[System.Serializable]
public class AtomCollectionItem<T> where T : AtomVariable
{
    public string id;
    public T variable;
}
```

**Comment by soraphis** [comment]
**idea**:
Maybe the Collection should be a listener, automatically listen to all Variables change events

and itself send an event whenever something in a collection was changed, so that you can batch multiple changes together and send one event for a bunch of changes.

this could be useful if your listensers would need to ensure that a another variable was set before (which itself could have a listener, ....)

**Comment by AdamRamberg** [comment]
> idea:
> Maybe the Collection should be a listener, automatically listen to all Variables change events
> 
> and itself send an event whenever something in a collection was changed, so that you can batch multiple changes together and send one event for a bunch of changes.
> 
> this could be useful if your listensers would need to ensure that a another variable was set before (which itself could have a listener, ....)

**Comment by soraphis** [comment]
> Another question, how would you identify what Variable was changed on the listener / receiver side?

have not made any thoughts about that :D was just brainstorming, had this thought and didn't want to forget about it, so i pasted it here.

**Comment by AdamRamberg** [comment]
Another idea (not entirely thought through). Should it be possible to add `AtomCollection`s inside an `AtomCollection`? If we enable that you can create something like a global store, much like [redux](https://redux.js.org/).

**Comment by AdamRamberg** [comment]
Added a first version in #110. Will close this issue. Lets create new issues if we want to add further functionality to the Collection.
