### ISSUE TITLE
[FEATURE] Add more contextual buttons to the editors

### ISSUE THREAD

**Issue by sampaiodias** [AdamRamberg/unity-atoms#72]
**Is your feature request related to a problem? Please describe.**
If I'm trying to debug a part of my code, I want to do it as fast as possible. However, sometimes the workflow of Atoms makes us go clicking on multiple objects to do what we need. For example, if I'm tweaking my AtomVariable in the inspector and want to raise the Changed Event, I have to double click on the event, raise it, and go back to the variable if I want to change it once again.

**Describe the solution you'd like**
Give us a button to trigger methods that are useful for the context you are seeing in the inspector. If you have a Variable with a Changed Event != null, add a button at the end of the inspector to raise the event. The same goes for other components, like Hooks. For example, instead of trying to reopen my scene to trigger a OnAwakeHook you could easily test it with a button.

**Describe alternatives you've considered**
I really can't think of other solution to this.

**Additional context**
Just a quick example:
![image](https://user-images.githubusercontent.com/14952766/68022161-4419cb80-fc82-11e9-8f1e-97ee2c724e21.png)

**Comment by soraphis** [comment]
> For example, if I'm tweaking my AtomVariable in the inspector and want to raise the Changed Event, I have to double click on the event, raise it, and go back to the variable if I want to change it once again.

as of https://github.com/AdamRamberg/unity-atoms/pull/70 changing the variable in playmode will raise a changed event (and also the changed with history)

**Comment by sampaiodias** [comment]
While I do agree that #70 helps, this sugestion is not limited to variables. But still, clicking a button is faster then manually changing your value (if you just want to test the event with the current or different value).

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! 

I think that we could add the Raise Event button for Events to a custom Event property drawer extending `AtomDrawer<T>`.

**Comment by sampaiodias** [comment]
@AdamRamberg that actually works too, for Events **and** Actions.

**Comment by AdamRamberg** [comment]
@sampaiodias Sounds good! 

My proposal would be to do the following then: 
- Add a Raise button and a Raise Value field for property drawers for Events and Actions
- Align property drawers with already existing Raise Editor for Events (I just now saw that there is a bug in this one where the Raise Value always is a `Toggle`). 
- Create templates for the Generator and adjust accordingly for proper generation. 

Please add if I have missed something. I believe this issue is ready to be developed. @sampaiodias would love a PR if you are up for it. Assigning you to the issue (no pressure though), you can always un-assign yourself if you want to.

**Comment by sampaiodias** [comment]
I would love to help with code, but for the moment I simply won't have time.

**Comment by soraphis** [comment]
> * Add a Raise button and a Raise Value field for property drawers for Events and Actions

*1 In an event (drawer) you have no information on where the event is used. Pressing the "raise" button will issue the question: what value to be raised?

adding a value field to this, wouldn't be much "drawer"-like. imho. for an editor (see *2) this is fine.

adding such a button to Variables would be easy though. (If approved i could add such a feature to #70)

**Comment by AdamRamberg** [comment]
@soraphis Good point! My thinking was that the current value of the Variable would be raised, but Events are not always tied to Variables. Back to the drawing board! 

Maybe just add a button to the Variable editor like @sampaiodias originally proposed would be the best solution?

**Comment by soraphis** [comment]
> Maybe just add a button to the Variable editor like @sampaiodias originally proposed would be the best solution?

i think so too. I've got the code for this already prepare in my local repo, but didn't made a pull request after reading here again and finding different feature specifications. so i thought I'd ask for clarification first

**Comment by AdamRamberg** [comment]
`i think so too. I've got the code for this already prepare in my local repo, but didn't made a pull request after reading here again and finding different feature specifications. so i thought I'd ask for clarification first`

Cool! I assign this issue to you then :)

**Comment by AdamRamberg** [comment]
Fixed in #70. Closing the issue.
