### ISSUE TITLE
[FEATURE] Show a preview of the Constant value

### ISSUE THREAD

**Issue by MeisterDerMagie** [AdamRamberg/unity-atoms#74]
**Is your feature request related to a problem? Please describe.**
In the inspector I can't see which value a Constant represents. I just see the reference to it.

**Describe the solution you'd like**
If there was a small readOnly preview of the Constant, it would make it more clear what values are actually used, without having to open the ScriptableObject.

**Additional context**
Quick sketch of the feature (made it in Photoshop, not actually coded due to my lack of experience in Editor programming):

![grafik](https://user-images.githubusercontent.com/40137439/68486948-7b6c1780-0242-11ea-931b-b248a016314b.png)

**Comment by MeisterDerMagie** [comment]
Maybe not only for Constants, but also for variables.

**Comment by AdamRamberg** [comment]
Thanks for the PR! Great feature addressed in #76

**Comment by AdamRamberg** [comment]
Solved in #89. Closing issue.
