### ISSUE TITLE
[FEATURE] Add Priority on Listener

### ISSUE THREAD

**Issue by Narudgi** [AdamRamberg/unity-atoms#75]
**Is your feature request related to a problem? Please describe.**
When an event has a lot of listener, we can be frustrated because some listeners should trigger before others to avoid bugs.

**Describe the solution you'd like**
A simple int value named priority (like in cinemachine) could help avoid this kind of situations.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by soraphis** [comment]
> When an event has a lot of listener, we can be frustrated because some listeners should trigger before others to avoid bugs.

sounds to me to be more like a fundamental problem in your project. could you provid a simple use-case where its clearly necessary to have this feature?

_____

the feature would not work with the C#-Style events (`OnEvent += ... `) this would mean to revert back to the self managed list of Actions, in this case an SortedList with a custom comparator that allows multiple entries for the same key.

**Comment by Narudgi** [comment]
Hey !
So I did some tests, and didn't find any necessary use of this feature in the end. I opened this issue to see if it would be something to consider and because a bug I got could have been fixed easier with this, but after some consideration, it's better like it is :)

I close this issue
