### ISSUE TITLE
[FEATURE] Setter on references

### ISSUE THREAD

**Issue by Saso222** [AdamRamberg/unity-atoms#77]
**Is your feature request related to a problem? Please describe.**
I do not know if this is intended, if so, just close this. When using references, having to access to Variable like ref._variable or to Values with ref._value to set its value is somewhat cumbersome.

**Describe the solution you'd like**
To be able to change the value of the reference without having to access to its Variable or Value.

**Describe alternatives you've considered**
Adding the same switch that exists on the **get** for the references to a new **set**, so just setting the reference value will set it on its according usage.

**Additional context**
Maybe something like this? I insist, maybe there's something I'm missing for this not to be here.
![image](https://user-images.githubusercontent.com/11753209/68529248-f265e680-02fc-11ea-90ea-5143179762e0.png)

**Comment by sampaiodias** [comment]
Seems like a valid and simple change to this file
https://github.com/AdamRamberg/unity-atoms/blob/master/Packages/Core/Runtime/References/AtomReference.cs

**Comment by soraphis** [comment]
@Saso222 feel free to create a PR about this. 

but note:
case(Constant) -> should throw a NotSupportedException.

while thinking about it. the constant should also throw when trying to modify its value. if not, it would behave the same as a variable

**Comment by Saso222** [comment]
Hey,
Just made the PR #78 . 
Please, let me know if there's something wrong. I added XML docs, but I'm not sure If I should do something with them.
Also, the example project is using an old version of the engine, maybe it's better to update that?
And, finally, let me know If do you want me to do something about us being able to modify the Constant value.
I'll set the PR ready for review if everything is ok.

**Comment by soraphis** [comment]
> And, finally, let me know If do you want me to do something about us being able to modify the Constant value.

no, just checked they are fine and trying to set their value will throw an "NotImplementedException" and will not change their value

**Comment by Saso222** [comment]
Sent the PR to review.

**Comment by AdamRamberg** [comment]
Late to the party, but hey what do you do 🤷‍♂ 

Thanks for submitting the PR! Looks like a great proposal. Me or @soraphis will take a look at the PR when we get the time.

**Comment by AdamRamberg** [comment]
Added in #78. Closing issue.
