### ISSUE TITLE
[FEATURE] Changed AddComponentMenu Listeners names

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#83]
**Is your feature request related to a problem? Please describe.**
![obraz](https://user-images.githubusercontent.com/51023959/68609531-c93c8600-04b5-11ea-9c19-3327353f278f.png)
If we try to add Listener component we have to type a name of variable. It would be easier to find and more clear to just type "Listener" and look at all Listeners and then find a type.

**Describe the solution you'd like**
Before we got only "Int" or "Int - Int" name, now we got "Int Listener" and "Int Int Listener". Just a small naming fix.

**Comment by sampaiodias** [comment]
The same goes for Hooks, it would be really useful to just type "hook" and see everything you can do.

**Comment by IceTrooper** [comment]
Ah, I don't use Hooks (Listeners only in few cases), didn't know that. However, you're right, it would be also easier.

**Comment by soraphis** [comment]
> Int Int Listener or Int x2 Listener

I'm for x2 because it preserve alphabetical ordering better

| Int | Long |
| --- | ------ |
|Int Int Listener | Long Listener|
|Int Listener | Long Long Listener|
|Int X2 Listener| Long X2 Listener|

`Int Int Listener` would be before `Int Listener`, but `Long Long Listener` after `Long Listener`

**Comment by IceTrooper** [comment]
Ok, give me a sign @AdamRamberg and I will make x2 or you can make it, it'd easy (@soraphis I also thought that when I had changed and checked that it got different alphabetical order hah)

**Comment by IceTrooper** [comment]
Ok, give me a sign @AdamRamberg and I will make x2 or you can make it, it'd easy (@soraphis I also thought that when I had changed and checked that it got different alphabetical order hah)
#84

**Comment by AdamRamberg** [comment]
@IceTrooper Sounds good to me! Please make the x2  change proposed by @soraphis.

**Comment by AdamRamberg** [comment]
Implemented in #84
