### ISSUE TITLE
[FEATURE] Base non-generic class for AtomAction; Parameterless Atom Listener

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#85]
**Is your feature request related to a problem? Please describe.**
We should have a base non-generic class for AtomAction. According to this: https://github.com/AdamRamberg/unity-atoms/issues/51#issuecomment-536749069 and this https://github.com/AdamRamberg/unity-atoms/issues/49#issuecomment-512791434.
Having base non-generic class gives us the possibility to add Atom Listener, which can handle all AtomEvent and use AtomAction.

**Describe the solution you'd like**
I'm going to make PR for that.

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! Sounds good to me. Assigning this issue to you :)

**Comment by IceTrooper** [comment]
It's done, you can take a look at #86 
Waiting to be added in canary :)
