### ISSUE TITLE
[BUG] Support for multiple lines in constant variables in AtomReference

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#87]
**Describe the bug**
How it looks like:
![obraz](https://user-images.githubusercontent.com/51023959/68626303-63fb8b80-04db-11ea-9de5-f6ccb689ad7d.png)
The same example hidden below next variable:
![obraz](https://user-images.githubusercontent.com/51023959/68626325-71187a80-04db-11ea-93c3-90271e484525.png)

**To Reproduce**
Using AtomReference with Variable which got more than one line in Editor (i.e. Rect).

I've already fixed it, I'll make PR.

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue! Would gladly accept a PR on this.

**Comment by IceTrooper** [comment]
Fixed in #88

**Comment by soraphis** [comment]
#88 merged
