### ISSUE TITLE
[FEATURE] Add option to use AtomEvents in a BehaviorSubject-like way 

### ISSUE THREAD

**Issue by richardsabow** [AdamRamberg/unity-atoms#92]
**Is your feature request related to a problem? Please describe.**
AtomVariables and related change events are great tools that help you in decoupling and separation of concerns, but I miss the option that allows you to somehow cache the value of the last change in the event.
AtomEvents work now like Subjects in Rx, but it'd be great if you could use them in a BehaviourSubject-like way.
I mean, if you have a GameObject which subscribes later than the inital/last change occurs on the variable, it doesn't know the current value of it, unless you pass them the variable explicitly.
However it would be better, if you'd need only to add the change listener, which would be called initially with the current value of the variable.

**Describe the solution you'd like**
It would be an easy solution, if you could set a field on events, whether it should store the value of the last emitted item. If it's set to true, it would save the last raised item in a private variable, and pass it to the listener's callback immediately on a new register call.
This way you wouldn't need a new `BehaviorAtomEvent` base type and new types for all of the existing descendants.

**Comment by AdamRamberg** [comment]
This is awesome! Are there other types of subjects that could be added as well? Maybe a ReplaySubject would be of use?

**Comment by richardsabow** [comment]
At the moment for my case I see the need only for getting the last value, but I guess it could be extended easily if needed – e.g. storing an array / list instead of one item.

**Comment by AdamRamberg** [comment]
If anyone is up for it I think this is a great feature and I would appreciate a PR!

**Comment by AdamRamberg** [comment]
Implemented in #114
