### ISSUE TITLE
[BUG] Could not find a part of path VariableValue.txt while generating Rect Atom

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#94]
**Describe the bug**
`DirectoryNotFoundException: Could not find a part of the path "D:\Users\IceTrooper\Documents\_Moje dokumenty\Repos\HungryWorm\unity-HungryWorm\Library\PackageCache\com.mambojambostudios.unity-atoms@b45438477515f19d29996841018cc2a10281678d\Packages\Core\Editor\Generator\Resources\UA_Template__Set{TYPE_NAME}VariableValue.txt"`
Something went wrong while generating new Atom (in this case I was trying to generate Rect). I got this file in provided directory.

**To Reproduce**
1. UnityAtoms -> Generator
2. Type Rect in "Type name" field.
3. Wait for generating files. The error will occur.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/51023959/69744515-9c889f80-1140-11ea-9823-ea721635e925.png)

**Environment**
 - OS: Windows 10 x64
 - Unity Version 2019.2.0f1
 - Version of Unity Atoms: v2.0 canary branch

**Comment by IceTrooper** [comment]
hmm, I think I got it. I added UnityEngine namespace to "Type namespace" field I don't have that error, but I have another:
`ArgumentOutOfRangeException: StartIndex cannot be less than zero.`

![obraz](https://user-images.githubusercontent.com/51023959/69744930-6bf53580-1141-11ea-93e5-e7ae47b4cb48.png)

**Comment by AdamRamberg** [comment]
@IceTrooper This issue seems to be solved? Got it working on my end at least: 
![Skärmavbild 2020-04-24 kl  06 27 18](https://user-images.githubusercontent.com/10260896/80175024-b695b380-85f4-11ea-86dc-335c90a68f61.png)

**Comment by AdamRamberg** [comment]
Should be resolved. Closing issue.
