### ISSUE TITLE
[BUG] Errors after importing scripts in 2018.4.14f1

### ISSUE THREAD

**Issue by fakegood** [AdamRamberg/unity-atoms#97]
Followed the instruction from Installation section to try on a new project, errors like these popped out,

`Library/PackageCache/com.mambojambostudios.unity-atoms-mono-hooks@2.1.0/Runtime/Hooks/Collider2DHook.cs(10,9): error CS0246: The type or namespace name 'Collider2DEvent' could not be found (are you missing a using directive or an assembly reference?)`

Error happens on 2018.4.14f1, doesn't appear for 2019.3.0f3.

**Comment by fakegood** [comment]
Submitted a pull request for this issue - https://github.com/AdamRamberg/unity-atoms/pull/98

**Comment by AdamRamberg** [comment]
Fixed in #98. Will be included in the package when the next version of Unity Atoms is released. Closing this issue.
